### ISSUE TITLE
Optional throttling for log appenders

### ISSUE THREAD

**Issue by ochedru** [dropwizard/dropwizard#2376] opened 2018-06-04 08:52 UTC
Situation: logs are sent to an external managed service through a specific log appender. Something goes wrong in the application and it generates a lot of logs very quickly. You do not notice the problem immediately. You end up with a hefty bill.

I was thinking of implementing a simple throttling mechanism in `AbstractAppenderFactory` and `AsyncAppenderBase`: maximum M messages over a given duration. Extra messages are discarded and not put into the queue.
Of course, this is disabled by default.

Do you think this is something of interest to Dropwizard users? If yes, I will submit a PR.

**Comment by nickbabcock** [comment] 2018-06-09 17:49
Yeah I've definitely been bitten by overly chatty logs caused by unfortunate situations. I'm curious if this can't already be solved through `queueSize` and `discardingThreshold` logging configurations. Let me know your thoughts 😄

**Comment by ochedru** [comment] 2018-06-10 12:18
If the remote log service has very good response times, I am afraid limiting the queue capacity will not help.

**Comment by nickbabcock** [comment] 2018-06-10 15:21
Very true. Yeah go ahead and file a PR. Having the ability for an opt-in throttle for any appender sounds good.

**Comment by nickbabcock** [comment] 2018-06-21 12:09
Closed by #2384

**Closed by nickbabcock** 2018-06-21 12:09 UTC
