### ISSUE TITLE
Getting  error java.io.IOException: Broken pipe when streaming for large audio file

### ISSUE THREAD

**Issue by jain0882** [dropwizard/dropwizard#1619] opened 2016-07-06 15:38 UTC
I am getting this error when receiving data from large streaming file.
```
 java.io.IOException: Broken pipe
! at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_60]
! at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.8.0_60]
! at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_60]
! at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_60]
! at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_60]
! at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170) ~[jetty-io-9.2.13.v20150730.jar:9.2.13.v20150730]
! ... 76 common frames omitted
! Causing: org.eclipse.jetty.io.EofException: null
```
I am using this these version of jersey in pom.xml 
```
<dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-client</artifactId>
            <version>2.22.1</version>
 </dependency>

<dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-common</artifactId>
            <version>2.22.1</version>
</dependency>
```

**Comment by joschi** [comment] 2016-07-06 16:10
@jain0882 Which version of Dropwizard are you using?

Could you provide a minimal example to reproduce your problem?

**Comment by jain0882** [comment] 2016-07-06 16:18
Thanks for your prompt response.
I am using 0.9.2 version of dropwizard.
Below is example to build response. I think I get the answer of mine problem, I need to use Range field of HTTP Request, but that wont stop above error.

private Response buildStream(final ByteBuffer byteBuffer) {
        StreamingOutput streamer = new StreamingOutput() {
            public void write(final OutputStream output) throws IOException, WebApplicationException {
                final WritableByteChannel outputChannel = Channels.newChannel(output);
                try {
                    outputChannel.write(byteBuffer);
                } finally {
                    outputChannel.close();
                }
            }
        };
        return  Response.ok(streamer).status(200).header(HttpHeaders.CONTENT_LENGTH, byteBuffer.limit()).build();
    }

**Comment by jain0882** [comment] 2016-07-06 17:01
Just to scratch previous message, Range doesnt solve the problem.

**Comment by nickbabcock** [comment] 2016-07-27 19:05
Not sure what the issue is, but I was able to set up an endpoint that transferred a 2.5GB file.

```java
@GET
@Path("/big-file")
public StreamingOutput getBigFile() {
    final java.nio.file.Path fpath = Paths.get("/tmp/biggie");
    return output -> {
        try (final SeekableByteChannel in = Files.newByteChannel(fpath, READ);
             final WritableByteChannel out = Channels.newChannel(output)) {
            fastChannelCopy(in, out);
        }
    };
}
```

I suspect it's not a Dropwizard issue.

**Comment by nickbabcock** [comment] 2016-08-19 15:11
Closing as not being able to be reproduced.

**Closed by nickbabcock** 2016-08-19 15:11 UTC
