### ISSUE TITLE
Bad Gateway (502) error on Dropwizard 1.3.x

### ISSUE THREAD

**Issue by usulkies** [dropwizard/dropwizard#2461] opened 2018-08-19 13:43 UTC
We're trying to upgrade the Dropwizard version from 1.2.x to 1.3.x.
Our services are deployed on AWS EBS, with nginx as LB proxy.
When changing the pom.xml dependency and deploying, we're starting to see, occasionally, "Bad Gateway" errors returned from nginx.
They're happening randomly, not at the same tests, and not all the time, but every 2-3 builds.
Usually in relatively heavy POST requests sending PDF content.

The nginx log shows errors like:
2018/08/14 05:03:07 [error] 12897#0: *11330 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.30.xx.xx, server: , request: "POST /some_url HTTP/1.1", upstream: "http://127.0.0.1:8080/some_url", host: "some_host.local"

2018/08/14 07:37:02 [error] 18575#0: *13099 writev() failed (104: Connection reset by peer) while sending request to upstream, client: 10.30.xx.xx, server: , request: "POST /some_url HTTP/1.1", upstream: "http://127.0.0.1:8080/some_url", host: "some_hostname"

We suspected jetty version, but the errors happens on version 1.3.5 and NOT on 1.2.8 although they're using the same jetty version.
If you have any explanations, ideas, missing configuration that we should have added except for just replacing the version in the pom file - please instruct us.

**Comment by usulkies** [comment] 2018-08-22 12:55
We enabled DEBUG level for jetty and dropwizard, but found nothing informative.
The requests that are failing do not appear at all in the logs. Not even headers, not to say the bodies.
We used tcpdump and this is how it looks in Wireshark:
![image](https://user-images.githubusercontent.com/10584010/44463120-65fbd500-a61f-11e8-9b50-f6b7ee92c41b.png)

It is filtered to show the data transmission between the dropwizard application port (8080) and the nginx ports (52822, 39808).
There are 4 requests here: 1 starts at 08:36, 2 at 09:04, 3 at 09:08 and 4 at 09:10.
1 and 4 were failed because of connection reset sent by the application.
They both started with TCP retransmission, but #2 also started with retransmission and didn't fail.
It seems that the problem is somewhere very low, maybe even not jetty level but java.net.
But why should it start happening after Dropwizard upgrade? (and it do happens again and again!)
Maybe it's something with dropwizard 1.3.x behaviour that causes in some indirect way to packet loss under heavy load (it happens during heavy concurrent load)?
Is there something from the /metrics endpoint that can help us with this analysis?
Many thanks, 
Uziel

**Comment by usulkies** [comment] 2018-08-23 05:32
Update: We managed to reproduce the problem with version 1.2.8, by decreasing the number of application instances to 1 in the load balancer.
This means that this happens because of the high concurrent load. 
Might there be something in DW 1.3.x that changed some configurations or added some overhead to the processing time, and made it more sensitive to load failures?
Can you suggest configuration changes to workaround the problem? keep-alive? rate? max connections? etc.

**Comment by abhrj** [comment] 2018-08-23 05:51
@Uziel

This is just a suggestion from a drop-newbie.

Since you can reproduce the problem with different versions of DW, you can,
if possible, try the test without DW, by directly using its dependencies.
This might help narrow down your investigation.

**Comment by usulkies** [comment] 2018-08-23 10:15
Another update: Currently it seems that the problem is solved by using a stronger machine instance in AWS. Moved from m3.medium to m5.large (8 cores), and no more Connection reset for a few builds until now. Sounds promising.
I'm closing the issue, although the question is still open, whether the problem get be solved by configurations to overcome the requests load. Maybe use nginx rate liimit, maybe something else.

**Comment by sgomadam** [comment] 2018-08-23 15:19
We notice a similar issue with DW 1.3.x. We use t3.medium. With concurrent load, it occasionally throws 502 or SocketTimeoutException(Connection reset). 

We also noticed that running with custom server config in a Docker image with OpenJDK fixes the issue.

Our default config does not have any custom server config. But if we add the following, we do not see any errors.

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080
      acceptQueueSize: 256

**Comment by isaki-x** [comment] 2018-08-23 20:53
It might be worth telling NGINX to reuse a pool of connections to your upstream DW applications.

https://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive

**Comment by biletnikov** [comment] 2018-08-29 07:29
We have exactly the same issue.
AWS ELB -> Dropwizard   (1.3.5)
and it drops 502 sometimes, especially if I wait 1-2 minutes and send about 40 requests in parallel, 5-10 of them maybe failed with 502. But the next attempt to send these 40 requests in few seconds later is usually successful. 

type:default did not help us.

server:
  type: default
  minThreads: 8
  maxThreads: 1024
  maxQueuedRequests: 1024
  applicationConnectors:
  - type: http
    port: 10022
  adminConnectors:
  - type: http
    port: 10023


ELB logs says that their receive 502 from the destination. At this moment we have one host behind ELB.

**Comment by sgomadam** [comment] 2018-08-29 12:31
Following workaround kind of solved the problem for our load. I am pretty sure with more load/less machine power, this issue might crop up again.

1) acceptQueueSize to 256. Dropwizard sets the queue size to be 128, if it is not provided in the config yaml.

**Comment by usulkies** [comment] 2018-08-29 13:44
@sgomadam The default for acceptQueueSize, according to DW documentation:
https://www.dropwizard.io/1.3.5/docs/manual/configuration.html#http
is: 

> The size of the TCP/IP accept queue for the listening socket.
So if it really works, the solution may be by changing DW configuration or changing the system defaults.

**Comment by sgomadam** [comment] 2018-08-29 13:55
yeah, changing the DW config to 256 and more works for us. 
Thing to note here is that the DW version 1.2.8 and 1.3.5 sets the default input queue size as 
the size of the TCP/IP accept queue for the listening socket(128 in  our case). For some reason, DW 1.2.8 does not have the problem with that configuration and 1.3.5 needs a larger queue size.

**Comment by biletnikov** [comment] 2018-08-29 15:10
@sgomadam 
thank you,   you are right!

I set acceptQueueSize to 1024  for the connector and the problem is solved!
As acceptQueueSize has default OS value in 1.3.5, it is not enough for small EC2 instances.

@usulkies 
you could back to smaller EC2 instances by increasing acceptQueueSize manually, if it was the only reason to scale them.

In general, the problem is not obvious and many people will face it, because DW is used to build microservices,  most of them are tiny and works on small cloud instances.

I would suggest to discard the default OS acceptQueueSize  or warn about the problem in the config.

**Comment by usulkies** [comment] 2018-08-29 20:35
OS Default tcp queue:
On m3.medium instance:
`cat /proc/sys/net/ipv4/tcp_max_syn_backlog`
128
On m5.xlarge instance:
512

So it makes sense that changing this parameter alone by configuration will solve the problem all the same.
And still, as some mentioned above - we have no clue why it happens a lot more on 1.3.x (I DID reproduce it on 1.2.8 using one instance for LB instead of 2)?
What is the overhead that was added in 1.3.x that causing the TCP queue to blow up?

**Comment by nickbabcock** [comment] 2018-08-30 05:57
> As acceptQueueSize has default OS value in 1.3.5

That was the intent, but there was a bug which made it not true. Take a look at https://github.com/dropwizard/dropwizard/pull/2430. The default accept queue should be equivalent to somaxconn, but only the first digit was read. This bug is fixed for a the next release

**Comment by usulkies** [comment] 2018-10-02 08:33
I see that version 1.3.6 is released without this fix. The fixing commit, 3e1e1ab6f34abbd12ea329cf23f9d11262cb6c69, is missing from the changes list.
When is it planned to be included?

**Comment by arteam** [comment] 2018-10-02 09:19
It's been merged only to the master branch. I will cut a 1.3.7 release with this change.

**Comment by nickbabcock** [comment] 2018-11-14 01:40
v1.3.7 was released on October 14th with the provided fix, so this issue will be closed

**Closed by nickbabcock** 2018-11-14 01:40 UTC
