### ISSUE TITLE
NoClassDefFoundError: IllegalName when serializing MetricRegistry

### ISSUE THREAD

**Issue by cmckn** [dropwizard/dropwizard#2401] opened 2018-06-19 17:47 UTC
I'm attempting to use an `ObjectMapper` to write my `Environment`'s `MetricRegistry` as a string, but am getting a strange error (on a freshly cloned build of Dropwizard, as well as `1.3.x`):

<pre>
com.fasterxml.jackson.databind.JsonMappingException: Failed to load class 'com.codahale.metrics.jetty9.InstrumentedQueuedThreadPool$$Lambda$82/1170032467$Access4JacksonSerializer9243fc45': IllegalName: com.codahale.metrics.jetty9.InstrumentedQueuedThreadPool$$Lambda$82/1170032467$Access4JacksonSerializer9243fc45 (through reference chain: com.codahale.metrics.MetricRegistry["metrics"]->java.util.Collections$UnmodifiableMap["org.eclipse.jetty.util.thread.QueuedThreadPool.dw-admin.size"])
	at com.example.helloworld.IntegrationTest.itShouldSerializeMetricsAsJSON(IntegrationTest.java:108)
Caused by: java.lang.IllegalArgumentException: Failed to load class 'com.codahale.metrics.jetty9.InstrumentedQueuedThreadPool$$Lambda$82/1170032467$Access4JacksonSerializer9243fc45': IllegalName: com.codahale.metrics.jetty9.InstrumentedQueuedThreadPool$$Lambda$82/1170032467$Access4JacksonSerializer9243fc45
	at com.example.helloworld.IntegrationTest.itShouldSerializeMetricsAsJSON(IntegrationTest.java:108)
Caused by: java.lang.NoClassDefFoundError: IllegalName: com.codahale.metrics.jetty9.InstrumentedQueuedThreadPool$$Lambda$82/1170032467$Access4JacksonSerializer9243fc45
	at com.example.helloworld.IntegrationTest.itShouldSerializeMetricsAsJSON(IntegrationTest.java:108)
</pre>

Simple reproduction using `dropwizard-example` application, by adding the following test to `com.example.helloworld.IntegrationTest`:
<pre>
    @Test
    public void itShouldWriteMetricRegistryAsString() throws JsonProcessingException
    {
        String json = RULE.getObjectMapper().writeValueAsString( RULE.getEnvironment().metrics() );
    }
</pre>

**Comment by joschi** [comment] 2018-06-19 18:16
@cmckn Please provide a minimal project to reproduce the issue.

**Comment by joschi** [comment] 2018-06-20 07:12
@cmckn Try using [`MetricRegistry#getMetrics()`](https://metrics.dropwizard.io/4.0.0/apidocs/com/codahale/metrics/MetricRegistry.html#getMetrics--).

**Comment by cmckn** [comment] 2018-06-20 22:15
Same issue. I've tried all the methods available in `MetricRegistry` to build a serializable `Collection` of `Metric`-s. No dice. I also can't for the life of me find where and how the `/metrics` endpoint on the administrative port is serviced. Thanks for taking the time!

<pre>
import io.dropwizard.Application;
import io.dropwizard.Configuration;
import io.dropwizard.setup.Environment;

public class MetricRegistryBugApplication extends Application<Configuration>
{
    public static void main( String[] args ) throws Exception
    {
        new MetricRegistryBugApplication().run( "server" );
    }
    
    @Override
    public void run( Configuration c, Environment e ) throws Exception
    {
        String json = e.getObjectMapper().writeValueAsString( e.metrics().getMetrics() );
    }
}
</pre>
will cause:
<pre>
com.fasterxml.jackson.databind.JsonMappingException: Failed to load class 'com.codahale.metrics.jvm.ThreadStatesGaugeSet$$Lambda$57/802243390$Access4JacksonSerializer998fedcf': IllegalName: com.codahale.metrics.jvm.ThreadStatesGaugeSet$$Lambda$57/802243390$Access4JacksonSerializer998fedcf (through reference chain: java.util.Collections$UnmodifiableMap["jvm.threads.deadlocks"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:291)
	at com.fasterxml.jackson.databind.SerializerProvider.reportMappingProblem(SerializerProvider.java:1223)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1342)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:510)
	at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddSecondarySerializer(PropertySerializerMap.java:90)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer._findAndAddDynamic(MapSerializer.java:1043)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer._findSerializer(MapSerializer.java:1148)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:716)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:639)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3905)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3219)
	at com.test.metricregistrybug.MetricRegistryBugApplication.run(MetricRegistryBugApplication.java:22)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.test.metricregistrybug.MetricRegistryBugApplication.main(MetricRegistryBugApplication.java:16)
Caused by: java.lang.IllegalArgumentException: Failed to load class 'com.codahale.metrics.jvm.ThreadStatesGaugeSet$$Lambda$57/802243390$Access4JacksonSerializer998fedcf': IllegalName: com.codahale.metrics.jvm.ThreadStatesGaugeSet$$Lambda$57/802243390$Access4JacksonSerializer998fedcf
	at com.fasterxml.jackson.module.afterburner.util.MyClassLoader.loadAndResolve(MyClassLoader.java:100)
	at com.fasterxml.jackson.module.afterburner.ser.PropertyAccessorCollector.generateAccessorClass(PropertyAccessorCollector.java:170)
	at com.fasterxml.jackson.module.afterburner.ser.PropertyAccessorCollector.findAccessor(PropertyAccessorCollector.java:97)
	at com.fasterxml.jackson.module.afterburner.ser.SerializerModifier.changeProperties(SerializerModifier.java:63)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanSerializer(BeanSerializerFactory.java:381)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanSerializer(BeanSerializerFactory.java:279)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:231)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:165)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1389)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1336)
	... 17 more
Caused by: java.lang.NoClassDefFoundError: IllegalName: com.codahale.metrics.jvm.ThreadStatesGaugeSet$$Lambda$57/802243390$Access4JacksonSerializer998fedcf
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:654)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.fasterxml.jackson.module.afterburner.util.MyClassLoader.loadAndResolve(MyClassLoader.java:94)
	... 26 more
</pre>

**Comment by nickbabcock** [comment] 2018-06-20 22:19
Aside: The `/metrics` endpoint comes from the [MetricsServlet](https://github.com/dropwizard/metrics/blob/3748f09b249f47a24ef868595fed4556ec5e92b1/metrics-servlets/src/main/java/com/codahale/metrics/servlets/MetricsServlet.java)

**Comment by cmckn** [comment] 2018-06-20 22:50
You beat me to it, but yes; the `MetricRegistry` is written to an `OutputStream` using `ObjectWriter#writeValue` within [MetricsServlet#doGet](https://github.com/dropwizard/metrics/blob/4.1-development/metrics-servlets/src/main/java/com/codahale/metrics/servlets/MetricsServlet.java#L166). My tests fail with the same error as above using equivalent calls. Can anyone reproduce this? I've seen the issue in several of my own projects using various Dropwizard versions, as well as the example application.

**Comment by cmckn** [comment] 2018-06-29 23:10
Yes, I discovered this outside of testing. I only used testing resources to get stack traces -- here's an [application](https://github.com/cmckn/metricregistrybug) with a `/metrics` endpoint. I get a 400 response. Thanks for looking into it!

**Comment by nickbabcock** [comment] 2018-06-30 00:08
Thank you @cmckn . I've narrowed it down to Jackson's afterburner module. Since I'm about to go on holiday for a week, I figured I'd do a quick brain dump in case someone figures it out. Below is a diff that minimally reproduces the issue within Dropwizard using one of our end to end tests. To replicate, do not run `App1` as a test, but run it as an application. Why this distinction is necessary escapes me.

```diff
diff --git a/dropwizard-e2e/src/main/java/com/example/app1/App1.java b/dropwizard-e2e/src/main/java/com/example/app1/App1.java
index 7c2ca98..8d91fb5 100644
--- a/dropwizard-e2e/src/main/java/com/example/app1/App1.java
+++ b/dropwizard-e2e/src/main/java/com/example/app1/App1.java
@@ -1,5 +1,7 @@
 package com.example.app1;

+import com.fasterxml.jackson.databind.ObjectMapper;
+import com.fasterxml.jackson.module.afterburner.AfterburnerModule;
 import com.github.mustachejava.MustacheNotFoundException;
 import io.dropwizard.Application;
 import io.dropwizard.Configuration;
@@ -18,6 +20,10 @@ import javax.ws.rs.ext.ExceptionMapper;
 public class App1 extends Application<Configuration> {
     public volatile boolean wasEofExceptionHit = false;

+    public static void main( String[] args ) throws Exception {
+        new App1().run("server");
+    }
+
     @Override
     public void initialize(Bootstrap<Configuration> bootstrap) {
         bootstrap.addBundle(new ViewBundle<>());
@@ -25,6 +31,8 @@ public class App1 extends Application<Configuration> {

     @Override
     public void run(Configuration config, Environment env) throws Exception {
+        (new ObjectMapper().registerModule(new AfterburnerModule())).writeValueAsString(env.metrics());
+
         // Ensure that we can override the default 404 response on an
         // empty optional and return a 204 instead.
         env.jersey().register(new EmptyOptionalNoContentExceptionMapper());
```

As a workaround, you can use `Jackson.newMinimalObjectMapper()` (which doesn't register the afterburner module), to serialize the registry

CC @cowtowncoder in case he happens to know off hand the caveats of the AfterBurner module

Disabling `OptimizedBeanDeserializer` and `ValueClassLoader` had no effect.

When I get back, I can look to whittle away at a more isolated test case.

**Comment by cmckn** [comment] 2018-07-02 15:59
>As a workaround, you can use Jackson.newMinimalObjectMapper() (which doesn't register the afterburner module), to serialize the registry.

You're a wizard -- this is totally adequate for now. Wish I had more to contribute, but I'm stumped on this. Could there be classpath differences between testing and not?

Enjoy your holiday and thanks again!

**Comment by nickbabcock** [comment] 2019-02-08 23:52
While this issue still affects the master branch, I'm closing the issue as the workaround using `Jackson.newMinimalObjectMapper()` seems adequate enough and only test code seems affected.

**Closed by nickbabcock** 2019-02-08 23:52 UTC

**Comment by cowtowncoder** [comment] 2019-02-09 01:01
I would actually like to get a reproduction for Afterburner as it seems like legit problem -- but not quite sure how to reproduce. I assume this is for lambda-generated class, and those probably should be ignored anyway, but trick is to figure out proper logic that does not require JDK 9.
