### ISSUE TITLE
JerseyClientBuilder will fail if there is another java rx implementation in the classpath

### ISSUE THREAD

**Issue by wlp1979** [dropwizard/dropwizard#3847] opened 2021-04-08 20:42 UTC
If you are using the JerseyClientBuilder and there is another implementation of the java rx Client interfaces in the class path, the call to [ClientBuilder.newClient might not return a JerseyClient](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java#L370). However, the next line below that will fail if a different client is returned. If instead the builder used `org.glassfish.jersey.client.JerseyClientBuilder.createClient`, it would be certain to get back a JerseyClient. This becomes a problem if you use a third party library that pulls in something like RestEasy.

**Comment by joschi** [comment] 2021-04-09 09:33
@wlp1979 Could you please provide a minimal project demonstrating this issue?

**Comment by wlp1979** [comment] 2021-04-12 16:10
Here is a repo that demonstrates the issue along with a modified client builder that works.

https://github.com/wlp1979/dw-jersey-example

**Comment by joschi** [comment] 2021-05-24 22:05
@wlp1979 Thanks for the repository to reproduce the issue!

> simply by including it in the classpath, the `JerseyClientBuilder` from `dropwizard-client` fails.

That's the whole core of the issue: You're putting a dependency on the classpath which registers an incompatible implementation of `javax.ws.rs.client.ClientBuilder`:
https://github.com/resteasy/Resteasy/blob/3.1.3.Final/resteasy-client/src/main/resources/META-INF/services/javax.ws.rs.client.ClientBuilder

My recommendation would be to not do this. 😉

`JerseyClientBuilder` is relying on the `ServiceLoader` to provide a compatible version of `javax.ws.rs.client.ClientBuilder` and doesn't have any influence on which implementation(s) are being provided.

It's up to the developer to make sure that there are no incompatible implementations of the JAX-RS SPI on the classpath.

**Comment by wlp1979** [comment] 2021-05-24 22:10
@joschi , unfortunately, that is not always possible. There are good reasons that we have two different implementations living in the same JVM. For example, it may be a required transitive dependency in another library.

The change inside the dropwizard `JerseyClientBuilder` are quite simple to implement and would make the `JerseyClientBuilder` always build a `JerseyClient`. Relying on the `ServiceLoader` means you can't be sure you are getting a `JerseyClient` out of the `JerseyClientBuilder`.

**Comment by mattnelson** [comment] 2021-05-25 16:46
Would this change fix the issue or surface the next jaxrs meta-inf service that assumes jersey?

**Comment by wlp1979** [comment] 2021-05-25 19:11
@mattnelson , the `SafeJerseyClientBuilder` class in my example repo will always return a JerseyClient. The main change is [this line](https://github.com/wlp1979/dw-jersey-example/blob/main/src/main/java/io/dropwizard/client/SafeJerseyClientBuilder.java#L357). In the end, it just bypasses the ServiceLoader all together and uses the Jersey code to build the client directly.

**Comment by wlp1979** [comment] 2021-05-25 19:30
I guess I could see an issue if someone has been relying on the `ServiceLoader` implementation to bring in their own subclass version of a `JerseyClient`.

**Comment by wlp1979** [comment] 2022-02-28 21:38
Ultimately, the current client builder code assumes that it will definitely get a `JerseyClient` back even though there is no guarantee that it will given the use of the `ServiceLoader`.

**Comment by zUniQueX** [comment] 2022-02-28 22:58
As we definitely need a `JerseyClient`, we should ensure that we get one. If the `ClientBuilder` cannot guarantee this, we shouldn't use it. Otherwise we could check, if the returned instance is a `JerseyClient` and throw a helpful exception, if it isn't.

If we have the ability to provide a valid implementation for all users through the `JerseyClientBuilder`, I think we should go this way. Letting `RuntimeException`s be thrown because of dependency issues is mostly very hard to debug for users.

**Comment by joschi** [comment] 2022-04-02 19:26
Resolved via #5093.

**Closed by joschi** 2022-04-02 19:26 UTC
