### ISSUE TITLE
logback's maxFileSize in combination with archivedFileCount not working as expected

### ISSUE THREAD

**Issue by ToastShaman** [dropwizard/dropwizard#1173] opened 2015-07-16 12:13 UTC
In commit 343680b8036a3d1bcb9432ca9b4d02b747c215a9 I've noticed that the `archivedFileCount` parameter in the YML configuration file is not working as expected.

The name suggests that older archives will be deleted once the `archivedFileCount` threshold has been reached. The `archivedFileCount` parameter is mapped to the [setMaxHistory](https://github.com/dropwizard/dropwizard/blob/343680b8036a3d1bcb9432ca9b4d02b747c215a9/dropwizard-logging/src/main/java/io/dropwizard/logging/FileAppenderFactory.java#L227) of the rolling policy.

Reading through Logback's documentation on [SizeAndTimeBasedFNATP](http://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedFNATP) it states that: 

*Size and time based archiving supports deletion of old archive files. You need to specify the number of periods to preserve with the maxHistory property.*

If you follow the `archivedFileCount` parameter you'll see that it is used by Logback as a way of specifying how many days log archives are allowed to be kept.

See [DefaultArchiveRemover](https://github.com/qos-ch/logback/blob/master/logback-core/src/main/java/ch/qos/logback/core/rolling/helper/DefaultArchiveRemover.java#L135) and [SizeAndTimeBasedArchiveRemover](https://github.com/qos-ch/logback/blob/master/logback-core/src/main/java/ch/qos/logback/core/rolling/helper/SizeAndTimeBasedArchiveRemover.java#L26)

I am happy to provide a pull request once I know how you want this to be fixed.

Cheers

**Comment by nicoruti** [comment] 2015-12-04 14:35
I'm facing the same issue as @ToastShaman (using dropwizard v0.9.1): the archivedFileCount does not trigger the removal of old files when using in conjunction with maxFileSize.
This leaves either the option to have one infinite large log file or infinite many log files, which are both not very useful for production-use.

**Comment by mattnelson** [comment] 2015-12-04 20:42
I have also noticed this 0.9 regression. My 0.8 based services are still rotating logs.

**Comment by arteam** [comment] 2015-12-05 15:45
See #1218. You would need to remove information about a log date from its archived name. For example, from `/var/log/app-%d{yyyy-MM-dd}-%i.log.gz` to `/var/log/app-%i.log.gz`.

I beleive, Logback's size and time based archiving supports only time-based rollover.

**Comment by mattnelson** [comment] 2015-12-10 21:19
I believe our issue may have been because the format was `/var/log/app-%d.log.gz` without the date pattern. But I will be switching over to the `%i` pattern only as that will better protect us against log flooding.

**Comment by nicoruti** [comment] 2015-12-11 08:39
@arteam Thanks for your hint with the date-pattern. Removing the date solves the issue. :+1:

**Comment by esigma5** [comment] 2016-01-07 13:30
I ran into the same problem and would like to have the feature of combining maxFileSize and archivedFileCount, as @ToastShaman offered

**Comment by jplock** [comment] 2016-01-17 14:53
Is this still an issue or would you mind submitting a pull request to implement this functionality if its supported by Logback?

**Comment by arteam** [comment] 2016-01-17 15:16
I beleive this should be fixed in Logback. Currently it doesn't support a rollover by the amount of log files (`FixedWindowRollingPolicy`), when a timestamp is present in log names (`TimeBasedFileNamingAndTriggeringPolicy`). For example, we can't keep 7 days of logs, but maximum 10 files. 

If anyone can provide an `ArchiveRemover` implemenation that supports such scenario, I will gladly review it. But I would encourage affected users to submit an issue or a pull request to Logback.

**Comment by nickbabcock** [comment] 2016-08-04 02:13
Closed by #1660

**Closed by nickbabcock** 2016-08-04 02:13 UTC
Labels: improvement, needs code
