### ISSUE TITLE
Jetty onIncompleteFlush 100% CPU 

### ISSUE THREAD

**Issue by eodonohoe** [dropwizard/dropwizard#2436] opened 2018-07-19 16:11 UTC
Encountered this in production using the Dropwizard 1.3.5 which depends on Jetty 9.4.11.v20180605 running on OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12).

I haven't found a relevant reported bug in the jetty project yet.

Similar report here:
http://dev.eclipse.org/mhonarc/lists/jetty-users/msg08551.html

**Linux thread**
 PID   TID USER       %CPU  TIME+ THREAD
 5979 18814 ubuntu     99.9  28:40.57 dw-1157 - POST /app/account/context

**Stack Trace of spinning thread:**
"dw-1157 - POST /app/account/context" #1157 prio=5 os_prio=0 tid=0x00007f67a9635800 nid=0x497e runnable [0x00007f676f3f0
000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ThreadLocal$ThreadLocalMap.getEntryAfterMiss(ThreadLocal.java:444)
        at java.lang.ThreadLocal$ThreadLocalMap.getEntry(ThreadLocal.java:419)
        at java.lang.ThreadLocal$ThreadLocalMap.access$000(ThreadLocal.java:298)
        at java.lang.ThreadLocal.get(ThreadLocal.java:163)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onIncompleteFlush(SslConnection.java:547)
        at org.eclipse.jetty.io.AbstractEndPoint$2.onIncompleteFlush(AbstractEndPoint.java:54)
        at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:332)
        at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
        at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:804)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
        at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:538)
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:795)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:846)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:240)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:515)

**Comment by nickbabcock** [comment] 2018-07-19 20:34
Thank you for reporting. Based on the mailing list you linked to (which was just posted last week!) it looks like it occurs without Dropwizard, so let's keep an eye on the mailing list (and if it gets reported as an issue in Jetty). so we can triage

**Comment by eodonohoe** [comment] 2018-09-24 13:58
Just following up.  I haven't had another instance of this issue.

It also looks like the fix to this might have been made here(see comments made July 11th and after): https://github.com/eclipse/jetty.project/issues/2233

**Comment by nickbabcock** [comment] 2018-09-24 21:43
Excellent, then it sounds like it has been fixed in Jetty 9.4.12, which the next version of dropwizard will use.

**Closed by nickbabcock** 2018-09-24 21:43 UTC
Labels: blocked

**Comment by pavanpatel20** [comment] 2020-03-31 07:30
We are also facing same issue in our jetty server (jetty-all-9.4.11.v20180605-uber) and jetty threads are taking more 300% to 400% CPU. This is not happening in all the servers, but in just one server. From this bug thread I understand that the fix is available in 9.4.12. But before upgrade need information on how to reproduce this issue. As this issue happened just once, we are bit confused how we will test our server after upgrading to 9.4.12 to validate that issue is fixed. Please provide more information on what are the possible causes of  jetty thread entering in this state.

"EndPoint-98" #98 prio=5 os_prio=0 tid=0x00007ff4f1171000 nid=0x3978 runnable [0x00007ff44a1dd000]
   java.lang.Thread.State: RUNNABLE
    at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onIncompleteFlush(SslConnection.java:545)
    at org.eclipse.jetty.io.AbstractEndPoint$2.onIncompleteFlush(AbstractEndPoint.java:54)
    at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:332)
    at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
    at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:804)
    at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
    at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
    at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:538)
    at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:795)
    at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:846)
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:240)
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:515)
    at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.write(ResponseWriter.java:303)
    at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:229)
    at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:299)
    at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
    at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
    - locked <0x00000005c72fd980> (a java.io.OutputStreamWriter)
    at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:135)
    at java.io.OutputStreamWriter.write(OutputStreamWriter.java:220)
    at org.glassfish.jersey.message.internal.ReaderWriter.writeToAsString(ReaderWriter.java:192)
