### ISSUE TITLE
NoClassDefFoundError - RequestLogFactory does not exist

### ISSUE THREAD

**Issue by VanDavv** [dropwizard/dropwizard#1438] opened 2016-01-31 08:07 UTC
When I changed to 1.0.0, and tried to launch my application, error below occured

> java.lang.NoClassDefFoundError: io/dropwizard/jetty/RequestLogFactory

Stack trace says, that the cause of this problem is in my configuration class, at the class definition. 
```
MyConfiguration.java

import com.fasterxml.jackson.annotation.JsonProperty;
import io.dropwizard.Configuration;
import io.dropwizard.db.DataSourceFactory;
import org.hibernate.validator.constraints.NotEmpty;

import javax.validation.constraints.NotNull;

public class MyConfiguration extends Configuration {

    @JsonProperty
    @NotNull
    private DataSourceFactory database;

    @JsonProperty
    @NotEmpty
    private String someString;


    public DataSourceFactory getDataSourceFactory() {
        return database;
    }

    public String getSomeString() {
        return someString;
    }
}
```
Version 0.9.2 works fine with given code, and all my dependencies are set to 1.0.0 version.

**Comment by arteam** [comment] 2016-02-06 15:12
Could you try the latest snapshot? Let's see if the fix in b7c8721 helps.

**Comment by djnawara** [comment] 2016-02-18 20:51
Not sure if this is helpful, but FYI…

I'm setting up a new app locally and tried to use the version listed on the site, 0.9.2, but I get the same problem above. I'd copied this out of [one of the examples](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/pom.xml#L14-L24):

```xml
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.dropwizard</groupId>
        <artifactId>dropwizard-bom</artifactId>
        <version>${project.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

It's causing dropwizard-core to pull in dropwizard-jetty but with _my_ version as declared in my pom, 1.0.0-SNAPSHOT. That dropwizard-jetty version exists and does not have a RequestLogFactory.

I took out the basepom stuff above and now things work.

**Comment by nickbabcock** [comment] 2016-05-24 20:19
Is this still happening? I am unable to reproduce this using 1.0.0-rc2

**Comment by joschi** [comment] 2016-05-31 16:25
I'm closing this issue as it cannot be reproduced.

@VanDavv Feel free to add a comment if the problem still occurs on the latest release candidate of Dropwizard 1.0.0.

**Closed by joschi** 2016-05-31 16:25 UTC
Labels: bug
