### ISSUE TITLE
@UnitOfWork is not wrapping the resource method with Hibernate session

### ISSUE THREAD

**Issue by ahmed-isam** [dropwizard/dropwizard#1253] opened 2015-09-16 16:01 UTC
Hi,

I have an issue where `@UnitOfWork` is not doing what it should, I've made sure that all the dependencies are in place in the POM file and the bundle and configuration are correct. I am using DW 0.6.2

Thanks

**Comment by ryankennedy** [comment] 2015-09-16 20:55
You're going to need to be a lot more specific about what is or is not happening.

**Comment by ahmed-isam** [comment] 2015-09-16 20:59
Basically I have a resource, and I am decorating the method with `@UnitOfWork` when I try to interact with DAO it throws `org.hibernate.HibernateException: No session currently bound to execution context`

**Comment by ryankennedy** [comment] 2015-09-16 21:10
Have you followed all of the instructions outlined [here](http://dropwizard.github.io/dropwizard/0.6.2/manual/hibernate.html)? In particular, are you invoking `bootstrap.addBundle(hibernate);`?

The easiest way to track down what's going on is going to be for you to submit enough of a code sample that we can reproduce the issue. There are a [number of tests](https://github.com/dropwizard/dropwizard/tree/v0.6.2/dropwizard-hibernate/src/test/java/com/yammer/dropwizard/hibernate/tests) for this functionality, which all pass. So I suspect you may have something configured incorrectly or you've found an unanticipated edge case. Either way, a code sample is our best bet of getting to the root of the issue.

**Comment by arteam** [comment] 2015-11-25 19:27
I am closing issue, because we can't reproduce it. Feel free to open a new issue, if the current one
exists in Dropwizard 0.8.5/0.9.1.

**Closed by arteam** 2015-11-25 19:27 UTC
