### ISSUE TITLE
JPMS builds fail due to split package (logback.core) in dropwizard-logging:1.3.0

### ISSUE THREAD

**Issue by christopher-johnson** [dropwizard/dropwizard#2312] opened 2018-03-20 18:03 UTC
1.3.0 exposes the `ch.qos.logback.core` package in the jar.  JPMS builds will fail for most use cases because of this as `logback-core` is used widely by other libraries.

**Comment by arteam** [comment] 2018-03-20 18:48
Yes, unfortunately, this one of painful points for Dropwizard. The project originally was designed to work with Logback configured from an application YAML file and the default logging configuration pokes around in Logback internals to make it work. We've managed to adjust Dropwizard to work with other logging providers (#1900, #2112), but you have to manually exclude the `logback` dependencies from the core and make sure `BootstrapLogging` is not loaded by the classloader, which is obviously a kludge. Maybe in Dropwizard 2.0 we will be able to implemented a more modular approach.

**Comment by pstorch** [comment] 2018-05-13 08:00
I think the problem is here https://github.com/dropwizard/dropwizard/blob/117cd08130cfebb1e78345672edf7b922d6e215e/dropwizard-logging/src/main/java/ch/qos/logback/core/recovery/ResilentSocketOutputStream.java#L54

This method is not overrideable from outside the package. Maybe we can ask over here  http://jira.qos.ch/secure/IssueNavigator.jspa to open it to be overrideable by any subclass?

**Comment by pstorch** [comment] 2018-05-18 07:03
I've opened a ticket here: https://jira.qos.ch/browse/LOGBACK-1400

**Comment by pstorch** [comment] 2018-05-20 19:47
I've also opened a PR for Logback to fix it: https://github.com/qos-ch/logback/pull/417

But there wasn't a commit to logback since February and there are a lot of open PRs. So I don't expect anything soon.
What else can be done in Dropwizard? Extract the `ResilentSocketOutputStream` class in it's own jar file (e.g. module) which can be excluded in case an app wants to use another logging implementation? 
Other ideas?

**Comment by willpdp** [comment] 2019-08-14 19:16
Is anyone aware of a workaround for this?

**Comment by willpdp** [comment] 2019-08-19 18:04
This is still an issue

**Comment by joschi** [comment] 2019-09-16 21:24
Addressed in #2312.

**Closed by joschi** 2019-09-16 21:24 UTC
Labels: blocked
