### ISSUE TITLE
dropwizard-example, maven build fails due to red test.

### ISSUE THREAD

**Issue by tobiassalem** [dropwizard/dropwizard#4325] opened 2021-10-04 15:36 UTC
Per the dropwizard-example readme, the following maven package command fails due to red test.
`./mvnw package`

```
[ERROR] Errors:
[ERROR]   ParanamerModuleTest.deserializePersonWithoutAnnotations:25  InvalidDefinition
[INFO]
[ERROR] Tests run: 56, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Dropwizard Project 2.1.0-SNAPSHOT .................. SUCCESS [  0.038 s]
[INFO] Dropwizard BOM 2.1.0-SNAPSHOT ...................... SUCCESS [  0.001 s]
[INFO] Dropwizard Dependencies 2.1.0-SNAPSHOT ............. SUCCESS [  0.001 s]
[INFO] Dropwizard Parent 2.1.0-SNAPSHOT ................... SUCCESS [  1.178 s]
[INFO] Dropwizard Utility Classes 2.1.0-SNAPSHOT .......... SUCCESS [  4.249 s]
[INFO] Dropwizard Jackson Support 2.1.0-SNAPSHOT .......... FAILURE [  4.115 s]
[INFO] Dropwizard Validation Support 2.1.0-SNAPSHOT ....... SKIPPED
[INFO] Dropwizard Configuration Support 2.1.0-SNAPSHOT .... SKIPPED
[INFO] Dropwizard Logging Support 2.1.0-SNAPSHOT .......... SKIPPED
[INFO] Dropwizard Lifecycle Support 2.1.0-SNAPSHOT ........ SKIPPED
[INFO] Dropwizard Metrics Support 2.1.0-SNAPSHOT .......... SKIPPED
[INFO] Dropwizard Jersey Support 2.1.0-SNAPSHOT ........... SKIPPED
[INFO] Dropwizard Servlet Support 2.1.0-SNAPSHOT .......... SKIPPED
[INFO] Dropwizard Jetty Support 2.1.0-SNAPSHOT ............ SKIPPED
[INFO] Dropwizard Health Checking Support 2.1.0-SNAPSHOT .. SKIPPED
[INFO] Dropwizard Request Logging Support 2.1.0-SNAPSHOT .. SKIPPED
[INFO] Dropwizard 2.1.0-SNAPSHOT .......................... SKIPPED
[INFO] Dropwizard Test Helpers 2.1.0-SNAPSHOT ............. SKIPPED
[INFO] Dropwizard HTTP Client 2.1.0-SNAPSHOT .............. SKIPPED
[INFO] Dropwizard Database Support 2.1.0-SNAPSHOT ......... SKIPPED
[INFO] Dropwizard JDBI3 Support 2.1.0-SNAPSHOT ............ SKIPPED
[INFO] Dropwizard Migrations 2.1.0-SNAPSHOT ............... SKIPPED
[INFO] Dropwizard Hibernate Support 2.1.0-SNAPSHOT ........ SKIPPED
[INFO] Dropwizard Authentication 2.1.0-SNAPSHOT ........... SKIPPED
[INFO] Dropwizard Multipart Form Support 2.1.0-SNAPSHOT ... SKIPPED
[INFO] Dropwizard Views 2.1.0-SNAPSHOT .................... SKIPPED
[INFO] Dropwizard Freemarker Views 2.1.0-SNAPSHOT ......... SKIPPED
[INFO] Dropwizard Mustache Views 2.1.0-SNAPSHOT ........... SKIPPED
[INFO] Dropwizard Metrics Support for Graphite 2.1.0-SNAPSHOT SKIPPED
[INFO] Dropwizard Asset Bundle 2.1.0-SNAPSHOT ............. SKIPPED
[INFO] Dropwizard HTTP/2 Support 2.1.0-SNAPSHOT ........... SKIPPED
[INFO] Dropwizard JSON logging 2.1.0-SNAPSHOT ............. SKIPPED
[INFO] Dropwizard Archetypes 2.1.0-SNAPSHOT ............... SKIPPED
[INFO] Dropwizard Archetype for Simple Java Services 2.1.0-SNAPSHOT SKIPPED
[INFO] Dropwizard Example Application 1.0.0-SNAPSHOT ...... SKIPPED
[INFO] Dropwizard Documentation 2.1.0-SNAPSHOT ............ SKIPPED
[INFO] Dropwizard End-to-end Tests 2.1.0-SNAPSHOT ......... SKIPPED
[INFO] Dropwizard Benchmarks 2.1.0-SNAPSHOT ............... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.020 s
[INFO] Finished at: 2021-10-04T17:22:35+02:00
[INFO] ------------------------------------------------------------------------
```

For the Record, the test is also red when running specifically in IntelliJ. 

```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.dropwizard.jackson.Person` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{ "name": "Foo", "surname": "Bar" }"; line: 1, column: 3]
```

Installed Java version per below, with IntelliJ language level set to 8 per the dropwizard maven pom.
java version "11.0.10" 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode).

For the Record, I have also tested upgrading to both Java 16 and 17, with the same result.

**Comment by joschi** [comment] 2021-10-04 15:40
@tobiassalem Which commit did you check out exactly?

**Comment by tobiassalem** [comment] 2021-10-04 15:41
> @tobiassalem Which commit did you check out exactly?

Latest master, today.

**Comment by joschi** [comment] 2021-10-04 16:05
I'm unable to reproduce the issue on a fresh clone of the `master` branch at 2436b3ac9cdc3f426f055bc8cc2a10270167cb21:
```
# git show -q --oneline
2436b3ac9 (HEAD -> master, origin/master, origin/HEAD) Bump Maven to version 3.8.3

# ./mvnw -V package
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: /path/to/.m2/wrapper/dists/apache-maven-3.8.3-bin/5a6n1u8or3307vo2u2jgmkhm0t/apache-maven-3.8.3
Java version: 11.0.12, vendor: Azul Systems, Inc., runtime: path/to/java/zulu-javafx-11.50.19/zulu-11.jdk/Contents/Home
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "11.5", arch: "x86_64", family: "mac"
[INFO] Scanning for projects...
[...]
[...]
[...]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Dropwizard Project 2.1.0-SNAPSHOT .................. SUCCESS [  0.027 s]
[INFO] Dropwizard BOM 2.1.0-SNAPSHOT ...................... SUCCESS [  0.000 s]
[INFO] Dropwizard Dependencies 2.1.0-SNAPSHOT ............. SUCCESS [  0.000 s]
[INFO] Dropwizard Parent 2.1.0-SNAPSHOT ................... SUCCESS [  0.878 s]
[INFO] Dropwizard Utility Classes 2.1.0-SNAPSHOT .......... SUCCESS [ 21.626 s]
[INFO] Dropwizard Jackson Support 2.1.0-SNAPSHOT .......... SUCCESS [ 22.722 s]
[INFO] Dropwizard Validation Support 2.1.0-SNAPSHOT ....... SUCCESS [ 14.789 s]
[INFO] Dropwizard Configuration Support 2.1.0-SNAPSHOT .... SUCCESS [ 40.102 s]
[INFO] Dropwizard Logging Support 2.1.0-SNAPSHOT .......... SUCCESS [ 21.607 s]
[INFO] Dropwizard Lifecycle Support 2.1.0-SNAPSHOT ........ SUCCESS [  9.871 s]
[INFO] Dropwizard Metrics Support 2.1.0-SNAPSHOT .......... SUCCESS [  9.672 s]
[INFO] Dropwizard Jersey Support 2.1.0-SNAPSHOT ........... SUCCESS [ 50.846 s]
[INFO] Dropwizard Servlet Support 2.1.0-SNAPSHOT .......... SUCCESS [ 17.694 s]
[INFO] Dropwizard Jetty Support 2.1.0-SNAPSHOT ............ SUCCESS [ 18.842 s]
[INFO] Dropwizard Health Checking Support 2.1.0-SNAPSHOT .. SUCCESS [ 22.244 s]
[INFO] Dropwizard Request Logging Support 2.1.0-SNAPSHOT .. SUCCESS [ 12.971 s]
[INFO] Dropwizard 2.1.0-SNAPSHOT .......................... SUCCESS [ 27.608 s]
[INFO] Dropwizard Test Helpers 2.1.0-SNAPSHOT ............. SUCCESS [ 41.919 s]
[INFO] Dropwizard HTTP Client 2.1.0-SNAPSHOT .............. SUCCESS [ 32.229 s]
[INFO] Dropwizard Database Support 2.1.0-SNAPSHOT ......... SUCCESS [ 15.339 s]
[INFO] Dropwizard JDBI3 Support 2.1.0-SNAPSHOT ............ SUCCESS [ 18.413 s]
[INFO] Dropwizard Migrations 2.1.0-SNAPSHOT ............... SUCCESS [ 24.247 s]
[INFO] Dropwizard Hibernate Support 2.1.0-SNAPSHOT ........ SUCCESS [ 36.594 s]
[INFO] Dropwizard Authentication 2.1.0-SNAPSHOT ........... SUCCESS [ 21.588 s]
[INFO] Dropwizard Multipart Form Support 2.1.0-SNAPSHOT ... SUCCESS [  7.986 s]
[INFO] Dropwizard Views 2.1.0-SNAPSHOT .................... SUCCESS [  9.814 s]
[INFO] Dropwizard Freemarker Views 2.1.0-SNAPSHOT ......... SUCCESS [ 12.150 s]
[INFO] Dropwizard Mustache Views 2.1.0-SNAPSHOT ........... SUCCESS [ 10.265 s]
[INFO] Dropwizard Metrics Support for Graphite 2.1.0-SNAPSHOT SUCCESS [ 10.372 s]
[INFO] Dropwizard Asset Bundle 2.1.0-SNAPSHOT ............. SUCCESS [  9.060 s]
[INFO] Dropwizard HTTP/2 Support 2.1.0-SNAPSHOT ........... SUCCESS [ 31.521 s]
[INFO] Dropwizard JSON logging 2.1.0-SNAPSHOT ............. SUCCESS [ 11.807 s]
[INFO] Dropwizard Archetypes 2.1.0-SNAPSHOT ............... SUCCESS [  0.089 s]
[INFO] Dropwizard Archetype for Simple Java Services 2.1.0-SNAPSHOT SUCCESS [  0.443 s]
[INFO] Dropwizard Example Application 1.0.0-SNAPSHOT ...... SUCCESS [ 51.019 s]
[INFO] Dropwizard Documentation 2.1.0-SNAPSHOT ............ SUCCESS [  0.221 s]
[INFO] Dropwizard End-to-end Tests 2.1.0-SNAPSHOT ......... SUCCESS [ 18.137 s]
[INFO] Dropwizard Benchmarks 2.1.0-SNAPSHOT ............... SUCCESS [  2.804 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:57 min
[INFO] Finished at: 2021-10-04T17:59:00+02:00
[INFO] ------------------------------------------------------------------------
```

@tobiassalem Did you modify anything in the repository or is it a "clean" checkout?

**Comment by zUniQueX** [comment] 2021-10-04 17:28
@joschi I had this issue too after upgrading to Jackson 2.13.0 in a separate project. Annotating the constructor parameters of the `Person` class with `@JsonProperty` annotations solved this problem. PR here: #4326

**Comment by joschi** [comment] 2021-10-04 19:30
@tobiassalem @zUniQueX Does this error also occur if your running the tests of `dropwizard-jackson` (and specifically ``) with Maven?

```

**Comment by zUniQueX** [comment] 2021-10-04 19:50
> ```
> ./mvnw test -pl dropwizard-jackson -Dtest=ParanamerModuleTest
> ```
In this configuration the test works fine. After I played around a bit further, this seems to be an error when running the tests with IntelliJ. The IntelliJ compilation process seems to produce a faulty output. When running against the IntelliJ created `target/` folder, the command line invocation would fail, while it succeeds if done a `clean` beforehand.

**Comment by tobiassalem** [comment] 2021-10-05 07:49
Maven version per below.
```
 ./mvnw -version
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: C:\Users\tobia\.m2\wrapper\dists\apache-maven-3.8.2-bin\1um3pu5poco57pibs3g92d6vrf\apache-maven-3.8.2
Java version: 11.0.10, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.10
Default locale: sv_SE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

Running the specific test with Maven results in the same red test result.
`./mvnw test -pl dropwizard-jackson -Dtest=ParanamerModuleTest`

```
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   ParanamerModuleTest.deserializePersonWithoutAnnotations:25  InvalidDefinition
[INFO]
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.668 s
[INFO] Finished at: 2021-10-05T09:46:48+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project dropwizard-jackson: There are test failures.
[ERROR]

```

**Comment by zUniQueX** [comment] 2021-11-12 20:11
The exception should be thrown from the call `Socket.connect(InetAddress, int)`. The [JavaDoc](https://docs.oracle.com/javase/8/docs/api/java/net/Socket.html#connect-java.net.SocketAddress-int-) for this actually specifies a `SocketTimeoutException`. I can reproduce the `SocketTimeoutException` on Windows, but also the `ConnectException` on Linux.

@joschi Should we stick to the JavaDoc and allow both exception types by doing something like `assertThatThrownBy(() -> tcpHealthCheck.check()).isInstanceOfAny(ConnectException.class, SocketTimeoutException.class)`?

**Comment by zUniQueX** [comment] 2021-11-16 15:48
I've raised a PR for consideration: #4423

**Comment by zUniQueX** [comment] 2021-11-17 22:53
@tobiassalem The issue with the exception types should be fixed. Can you please verify this?

**Comment by joschi** [comment] 2022-02-10 16:43
Closing issue due to inactivity of original author.

**Closed by joschi** 2022-02-10 16:43 UTC
