### ISSUE TITLE
Update the tech empower benchmarks

### ISSUE THREAD

**Issue by carlo-rtr** [dropwizard/dropwizard#1010] opened 2015-04-23 13:12 UTC
One think we should do is make sure that empower benchmark is using the latest code.

https://www.techempower.com/benchmarks/

https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Java/dropwizard

**Comment by carlo-rtr** [comment] 2015-04-23 13:47
@yunspace is taking ownership. Github assignee has to be a committer in the project, I'll take that.

**Comment by yunspace** [comment] 2015-04-28 10:43
I've got in contact with framework-benchmark folks and found out why dropwizard and dropwizar-mongodb tests failed to run for round 10: https://github.com/TechEmpower/FrameworkBenchmarks/issues/1545 

It appears both had issues obtaining port 9000. As a quick fix I propose to change the ports to something else. At least not have dropwizard and dropwizard-mongodb both listening on same port 9000.

As part of the benchmak update, I plan to upgrade dropwizard version to `0.8.1` and use `java8-bundle`. If anyone has any suggestions or feedback please let me know.

**Comment by carlo-rtr** [comment] 2015-04-30 13:57
That sounds reasonable. I think it would be nice to show up on the json serialization test too. Jackson is a mature library, so I suspect we will do well.

https://www.techempower.com/benchmarks/#section=data-r10&hw=peak&test=json

**Comment by yunspace** [comment] 2015-05-01 01:40
yes I'll aim to implement all of the relevant tests if possible.

**Comment by yunspace** [comment] 2015-06-17 11:24
Initial local tests on my laptop show Dropwizard 0.8.1 is more than 3x times faster than 0.7.1 Made a tweet with screenshots here: https://twitter.com/yunzhilin/status/611130225355677697

**Comment by carlo-rtr** [comment] 2015-06-18 16:39
Awesome, great work! Is there any work remaining? Should we close this issue?

**Comment by yunspace** [comment] 2015-06-19 06:15
Thanks, it's been good learning experience too. I just have one more optimisation I want to try out. Java8 lambdas + parallel streams

**Comment by yunspace** [comment] 2015-07-11 14:00
After playing around a bit more with the Techempower benchmarks on my local machine, I realised I actually made a mistake previously in interpreting the results:

- Dropwizard 0.8.1 is faster by a factor of 3 compared to 0.7.1 for the Fortunes HTML tests only. This is likely to be due to upgrade in the Mustache template library.
- All other tests show decreases in performance. Most obvious are the JSON and Plain Text tests, which simply prints single messages with no DB interaction. It seems that since upgrading to Jersey 2.0, the Resources are taking longer to respond?

I've compiled the averages of my test results into a single easy to read graph: https://docs.google.com/spreadsheets/d/1PL1kGfyEA9NVwa1uBA3OOmQ_fEs6wkroCgm94TUbW3g/edit?usp=sharing

I tried a few things such as upgrading to Java8 or use parallel streams but they didn't make much difference and it doesn't feel quite clean. I don't think I will have much time to spend on this anymore. Let's close this for now and I will re-visit for 0.9.X

**Comment by cowtowncoder** [comment] 2015-07-17 21:14
FWIW, I suspect that almost all overhead comes directly from Jersey JAX-RS endpoint handling.
JAX-RS spec is unfortunately defined in such a way that it imposes much more dynamic overhead for calls than necessary (for example, since endpoints are defined by classes, which are static, most introspection could be done just once -- but is actually done for each and every call).
By the time DropWizard gets hold of request there isn't much to be done. And it may not be possible for Jersey to do much either.

Ideally JAX-RS specification did divide initialization steps into 2 parts: things that only depend on static class definitions; and things that vary by request. But I doubt much can be done at this point, due to maturity of the spec and implementations.

**Comment by yunspace** [comment] 2015-07-18 13:07
Thanks @cowtowncoder you confirmed my sneaky suspicion in that Jersey is likely to be the culprit. There are other JAX-RS implementations out there such as RestEasy (some interesting benchmarks [here](http://dummywarhead.blogspot.com.au/2014/12/performance-comparison-of-jax-rs-20.html) too), but that won't be a easy change as the DW ecosystem is deeply rooted in Jersey.

**Comment by yunspace** [comment] 2015-08-09 14:28
Just got an idea, if I use a `@Singleton` resource that may reduce some of the overhead of introspecting and creating a new resource each time. Will try this out.

**Comment by cowtowncoder** [comment] 2015-08-09 22:39
It would also be great to build a local setup to profile overhead for simple calls. That should give some indication as to where most time is spent.

**Comment by yunspace** [comment] 2015-08-19 02:25
@cowtowncoder yes there is another card for adding local benchmarks https://github.com/dropwizard/dropwizard/issues/963

as for the Techempower benchmarks, I've tried the `@Singleton` approach and it didn't really make much difference. The preview results for Round 11 are out https://www.techempower.com/benchmarks/previews/round11/ and DW isn't doing so well. I might try and upgrade to the latest 0.9.0 rc and see the latest versions of Jersey has any improvements.

**Comment by nickbabcock** [comment] 2016-03-30 03:01
I looked into the performance issues and the lowest hanging fruit are to use Jersey's `StreamingOutput ` and Jackson's Streaming API in combination, which yields 2-3x improvement. The next level of improvement is eschewing Jersey and using Http Servlets in Jetty, which yields a 10x improvement over vanilla performance. Unfortunately, I don't think any of these improvements are considered realistic, and probably shouldn't be merged into the benchmarks.

May be worth it to revisit once 1.0 is out

**Closed by nickbabcock** 2016-03-30 03:01 UTC

**Comment by cowtowncoder** [comment] 2016-03-30 04:20
@nickbabcock thank you for the sanity check. This seems to confirm that there is quite a bit of overhead for dynamic dispatch, much of which would ideally be optimized away, but probably in practice can not be (due to JAX-RS rules).
