### ISSUE TITLE
Upgraded Jackson/Joda causes breaking change on `DataTime`

### ISSUE THREAD

**Issue by kilemensi** [dropwizard/dropwizard#1195] opened 2015-07-28 15:20 UTC
I see `RC4-SNAPSHOT` has upgraded jackson library to the latest `2.6.0` and withit comes a breaking change where previously `2015-07-28` would be perfectly serialized into a joda `DataTime` object, now any request containing Resource in this format is denied by dropwizard as `400: Bad Request`. It requires a full ISO format string like `2015-07-28T22:30:35Z`.

Was this discussed previous? Personally I can't think of any reason why this change is required and especially since `RC3` works just fine.

/cc @cowtowncoder

**Comment by cowtowncoder** [comment] 2015-07-28 17:20
Quick comment: is this:

https://github.com/FasterXML/jackson-datatype-joda/issues/70

the root cause?

Breakage is unintentional and surprising; I assume the joda issue is the root cause and will add more information there. We should be able to fix this for 2.6.1.

**Comment by arteam** [comment] 2015-07-29 07:06
Yikes. Thanks, @kilemensi, for testing release candidates and reporting this.

@cowtowncoder, do you plan to release *jackson-datatype-joda* 2.6.1 soon? If not, we will probably rollback to 2.5.* stream and move 2.6.* update to Dropwizard 1.0.

**Comment by cowtowncoder** [comment] 2015-07-29 16:52
@arteam What I can do very quickly is to release a micro-patch of 2.6.0.1, both for Joda and jsr-310 (java 8 time). I don't know when full 2.6.1 will be released, but I usually will try to pack in a few more fixes.
Micro-patch just means that it is not part of full patch release, and is done for critical breakages. This one would qualify.

I will actually go ahead and cut the micro-release, just in case.

**Comment by cowtowncoder** [comment] 2015-07-29 17:20
With that, there's now 2.6.0-1:

http://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.6.0-1/

of Joda module. I will release 2.6.0-1 of jsr-310 module later tonight as well.

I understand if decision is made to stay with 2.5(.4), for DropWizard 0.9, but wanted to make sure there is an alternative.

**Comment by arteam** [comment] 2015-07-29 17:50
Okay, thanks. I've updated _jackson-datatype-joda_ to 2.6.0-1 in master.
@kilemensi, could you test the latest RC4 snapshot?

**Comment by kilemensi** [comment] 2015-07-29 18:37
@arteam Tested and works as expected. Thanks @cowtowncoder

**Comment by cowtowncoder** [comment] 2015-07-29 18:38
Thank you for reporting the problem, apologies for causing it.

**Closed** 2015-07-30 13:56 UTC
