### ISSUE TITLE
Dropwizard slf4j+logback 

### ISSUE THREAD

**Issue by sathish-hike** [dropwizard/dropwizard#1848] opened 2016-12-07 14:02 UTC
This issue is related to https://github.com/dropwizard/dropwizard/issues/1367
We are unable to use Phoenix Client in our existing DropWizard application. I see that incompatibility issues with Spark+DropWizard too.
Currently both logback and slf4j are required dependencies in Dropwizard. And since you can only have one implementation of slf4j in your class path it's not possible to use slf4j-log4j12, for example.
This is the current design. Please keep this ticket open and do not lock it. We'll use it to track the fix/pr for the same. If its closed, no one will think about it.

**Comment by joschi** [comment] 2016-12-07 14:04
Duplicate of #1367.

A PR can reference #1367 despite it's locked, so no need to create new issues for this.

**Closed by joschi** 2016-12-07 14:04 UTC

**Comment by sathish-hike** [comment] 2016-12-07 14:16
@joschi This is the real world issue that we are facing.
Why are you closing it? If its a design decision, lets keep it open so that our committers can track it and provide an easy solution. Opinionated frameworks won't stay for long.
Created this new one since you've locked https://github.com/dropwizard/dropwizard/issues/1367
Please reopen this issue https://github.com/dropwizard/dropwizard/issues/1848 or https://github.com/dropwizard/dropwizard/issues/1367
Only the resolved issues should be closed.

**Comment by arteam** [comment] 2016-12-07 15:25
FWIW, I tried to hack a little bit on support external logging frameworks in Dropwizard in the `remove_logback_dependency` branch. You can see some progress [here](https://github.com/dropwizard/dropwizard/commit/b375d5e201b7d6debfc25e2f6316d8e7f5345be8). I tried to remove explicit dependencies on Logback and use the sl4fj API whenever possible. In the end, I got an example application running with log4j, but that's it. There is a lot of work in that direction, but this commit could be a good start.

**Comment by arteam** [comment] 2016-12-07 15:30
Follow-up for the latest comment: 

The example application had Logback excluded in the pom.xml:
```xml
  <dependencies>

        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-core</artifactId>
            <version>1.1.0-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-access</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>log4j-over-slf4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.21</version>
        </dependency>

    </dependencies>
```

and external logging enabled in the Dropwizard configuration:
```yml
server:
  type: simple
  applicationContextPath: /application
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
  requestLog:
    type: external
logging:
  type: external
```

**Comment by sathish-hike** [comment] 2016-12-07 17:30
I tried above solution, still facing same issue. Here is my error report:

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/sathish/workspace/test/lib/phoenix-4.4.0.2.4.2.0-258-client.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/sathish/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.1.7/9865cf6994f9ff13fce0bf93f2054ef6c65bb462/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Exception in thread "main" java.lang.IllegalStateException: Unable to acquire the logger context
	at io.dropwizard.logging.LoggingUtil.getLoggerContext(LoggingUtil.java:46)
	at io.dropwizard.logging.BootstrapLogging.bootstrap(BootstrapLogging.java:45)
	at io.dropwizard.logging.BootstrapLogging.bootstrap(BootstrapLogging.java:34)
	at io.dropwizard.Application.<init>(Application.java:24)
	at com.test.MyApplication.<init>(MyApplication.java:19)
	at com.test.Application.main(MyApplication.java:23)
:run FAILED

FAILURE: Build failed with an exception.
```

**Comment by arteam** [comment] 2016-12-07 17:49
You would need to build a snapshot Dropwizard version from the branch and test on a separate project. This is needed to make sure Logback is not present in the classpath.

**Comment by vybs** [comment] 2017-04-26 19:23
thanks much for fixing this. when will this make into the official release @arteam

**Comment by monishkumarg** [comment] 2017-05-03 01:38
Hi Arteam,

If I remove logback from dependency, I am getting java.lang.NoClassDefFoundError: ch/qos/logback/classic/Level Error.

Please let me know what i can do for this case.

Thanks,

**Comment by kedarr** [comment] 2018-07-06 14:55
@monishkumarg Were you able to resolve the issue ?

**Comment by scho** [comment] 2020-06-04 13:13
@monishkumarg + @kedarr:
Make sure to override `io.dropwizard.Application#bootstrapLogging` in your application class as described here:
https://www.dropwizard.io/en/stable/manual/core.html#logging

**Comment by nsoft** [comment] 2024-08-28 18:48
> @monishkumarg + @kedarr: Make sure to override `io.dropwizard.Application#bootstrapLogging` in your application class with an empty method as described here: https://www.dropwizard.io/en/stable/manual/core.html#logging

This does not seem to work in all cases. Dropwizard applications extend the Application class which contains an import statement for `ch.qos.logback.classic.Level`, and the method `io.dropqizard.application#boostrapLogLevel` returns `Level`

(https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/Application.java#L32)

Thus any framework that calls getDeclaredMethods  tries to load the method, and bombs with NoClassDefFoundError... one such library is [Junit5](https://github.com/junit-team/junit5/blob/r5.11.0/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java#L1557). So testing anything that touches dropwizard requires logback dependencies to be safe from .... but plenty of other runtime libraries use reflection as well, so I think https://github.com/dropwizard/dropwizard/issues/1367 is insufficient for general usage.
