### ISSUE TITLE
Documentation is out of date for Dropwizard Views

### ISSUE THREAD

**Issue by johnstok** [dropwizard/dropwizard#930] opened 2015-03-08 16:53 UTC
The [documentation for Dropwizard views](http://dropwizard.io/manual/views.html) does not reflect the fact that in 0.8.0 you must now implement a concrete subclass of `ViewBundle`. I think this change was introduced in the following commit: https://github.com/dropwizard/dropwizard/commit/1ffa692833bc4f14b9065ded24f19634724d6311.

**Comment by joschi** [comment] 2015-03-08 22:41
Duplicate of #925.

**Closed by joschi** 2015-03-08 22:41 UTC
