### ISSUE TITLE
Server starts and stops immediately when both enableVirtualThreads and enableAdminVirtualThreads are set to true

### ISSUE THREAD

**Issue by ochedru** [dropwizard/dropwizard#8137] opened 2023-12-28 11:24 UTC
To reproduce, use  branch release/5.0.x and a Java 21 runtime:
- edit `example.yml` and add `enableVirtualThreads: true` and `enableAdminVirtualThreads: true` to the `server` section.
- start the server as described in the [readme](https://github.com/dropwizard/dropwizard/tree/release/5.0.x/dropwizard-example)

Note: this works fine with only `enableVirtualThreads: true` or `enableAdminVirtualThreads: true` ; the issue appears only when both options are set.

**Comment by zUniQueX** [comment] 2023-12-28 18:16
@ochedru Thanks for reporting this!

I've also reproduced the bug with the `SimpleServerFactory` and `enableVirtualThreads` set to `true`.

**Comment by zUniQueX** [comment] 2023-12-28 18:40
When using virtual threads, an `AsynchronousCloseException` is thrown to Jetty's `AbstractConnector` class while waiting to accept connections. When overriding the Dropwizard application's `main` method and calling `Server.join()` there, the issue doesn't occur. So it seems like the thread pool gets closed when the connection handling isn't done by blocking platform threads.

I'll investigate, if we can/should call `Server.join()` on the Dropwizard side or if we shouldn't do this because it happens inside the CLI execution.

**Comment by cty123** [comment] 2023-12-29 10:11
I had the same issue, and here is what I have found out. Typically this is how the main function of a Dropwizard application looks like,

```java
public static void main(String[] args) throws Exception {
    new ExampleApplication().run(args);
}
```

such that the main thread exits right after starting the application. This was fine before because the JVM wouldn't exit until all non-daemon threads have exited, which would never happen as there were admin thread pool executor as well as application executor executor each with non-daemon threads in the thread pool. ([doc](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.html#isDaemon())) 

> Platform threads are designated daemon or non-daemon threads. When the Java virtual machine starts up, there is usually one non-daemon thread (the thread that typically calls the application's main method). The [shutdown sequence](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Runtime.html#shutdown) begins when all started non-daemon threads have terminated. Unstarted non-daemon threads do not prevent the shutdown sequence from beginning.

Starting with JDK21 together with the enablement of virtual threads, this is no longer the case, because virtual thread can not be a non-daemon thread([doc](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.html#isDaemon())),

> Tests if this thread is a daemon thread. The daemon status of a virtual thread is always true.

So what happens right now is that, when virtual thread is enabled for both admin and application connectors, the main thread is the only non-daemon thread(unless you spawn manually either in main or with dependency injection), such that when the main threads exits, the JVM immediately detects the termination of all non-daemon threads, and choose to shutdown, ignoring the virtual thread executor.

The solution I had was that, since the main thread is the only non-daemon thread, I can just make sure it doesn't exist, unless certain things happens like interrupt signal, so I just let the main thread to wait for itself,

```java
public static void main(String[] args) throws Exception {
    new ExampleApplication().run(args);
    
    Thread.currentThread().join();
}
```

Ideally, I would like the run function to return a future or run blocking until completion, like,

```java
public static void main(String[] args) throws Exception {
    new ExampleApplication().run(args).wait();
}
```

PS: Please let me know if there's better way to solve this.

**Comment by cty123** [comment] 2023-12-29 11:44
Btw, this issue also exists in DW3 as I just ran into a few weeks before, I believe it also exists in DW4, but I haven't had a chance to reproduce on it.

**Comment by zUniQueX** [comment] 2023-12-29 11:56
@cty123 The issue exists due to the presence of the `enableVirtualThreads` flag. This flag is present in the versions 3.x, 4.x and 5.x. After we have a solution, this will be merged to all those branches.

**Closed as completed** 2024-01-26 09:36 UTC
Labels: bug
