### ISSUE TITLE
Null pointer Exception (NPE) creating ResourceTestRule

### ISSUE THREAD

**Issue by artemabalmasov** [dropwizard/dropwizard#828] opened 2014-12-30 19:00 UTC
Good day
Will be awesome if you can help me
I'm trying to upgrade dropwizard from 0.6 to 0.8. And Then I run my tests i get NPE:
```java
java.lang.NullPointerException
	at org.glassfish.jersey.test.JerseyTest.tearDown(JerseyTest.java:634)
	at io.dropwizard.testing.junit.ResourceTestRule$1.evaluate(ResourceTestRule.java:144)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
```
However, I'm able to run tests from example project without any issues.
It looks liek it's failing due to unknown reasons in InMemoryTestContainerFactory:
```java
    public TestContainer create(final URI baseUri, final DeploymentContext context) throws IllegalArgumentException {
        return new InMemoryTestContainer(baseUri, context);
    }
```
Since exception or smth is consumed I have no idea why it's failing. Have you faced such issues ? 
I'm thinking of amending ResourceTestRule#apply method to add some catch\log\rethrow logic since original exception got suppresed by NPE later.
May it  be linked with that I'm trying to use guice DI instead of HK2.
Thank you!

**Comment by artemabalmasov** [comment] 2015-01-02 15:24
Hi Joschi
Issue is that i got exception on startup. 
Resource :
```java
import com.google.common.base.Strings;

import java.util.Collection;
import java.util.Set;
import javax.inject.Inject;
import javax.servlet.http.HttpServletRequest;
import javax.ws.rs.Consumes;
import javax.ws.rs.CookieParam;
import javax.ws.rs.DefaultValue;
import javax.ws.rs.FormParam;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
...
@Path("Path")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_FORM_URLENCODED)
public class EmailChangeResource {
...
    @Inject
    private EmailChangeRequestBuilder emailChangeRequestValidator;

    @POST
    @Path(Routes.EMAIL_CHANGE_AJAX)
    public Response changeEmailAjax(
            @CookieParam(Cookie.NAME) String cookie,
            @FormParam("newEmail") @DefaultValue(value = "") String newEmail,
            @FormParam("source") @DefaultValue(value = "") String source,
            @Context HttpServletRequest httpRequest) {
...
}
}
```
Test:
```java
import com.sun.jersey.core.util.MultivaluedMapImpl;
import io.dropwizard.testing.junit.ResourceTestRule;
import org.glassfish.jersey.client.ClientResponse;
import org.junit.*;
import org.junit.runner.RunWith;
import org.mockito.Mockito;
import org.mockito.runners.MockitoJUnitRunner;

import javax.servlet.http.HttpServletRequest;
import javax.ws.rs.client.Entity;
import javax.ws.rs.client.Invocation;
import javax.ws.rs.core.Cookie;
import javax.ws.rs.core.MultivaluedMap;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@RunWith(MockitoJUnitRunner.class)
public class EmailResourceTest{
   @ClassRule
    public static ResourceTestRule resources  = ResourceTestRule.builder()
            .addResource(new EmailChangeResource())
            .build();
    @Test
    public void testPositive() throws Exception {
        ClientResponse response = queryResource("/email/change", validCookie(), validMpsCookie(), VALID_NEW_EMAIL, VALID_SOURCE);
        Assert.assertEquals(200, response.getStatus());
        ...
    }
}
```
May It be linked with JNI ?
Thank you!

**Comment by joschi** [comment] 2015-01-03 16:39
@artemabalmasov I couldn't reproduce your problem with the following test class:

```java
package io.dropwizard.testing.junit;

import org.junit.Assert;
import org.junit.ClassRule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.runners.MockitoJUnitRunner;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

@RunWith(MockitoJUnitRunner.class)
public class Issue828 {
    @ClassRule
    public static ResourceTestRule resources = ResourceTestRule.builder()
            .addResource(new TestResource())
            .build();

    @Test
    public void testPositive() throws Exception {
        Response response = resources.client().target("/").request()
                .accept(MediaType.APPLICATION_JSON_TYPE)
                .get();
        Assert.assertEquals(200, response.getStatus());
    }

    @Produces(MediaType.APPLICATION_JSON)
    @Path("/")
    public static class TestResource {
        @GET
        public Response foo() {
            return Response.ok().build();
        }
    }
}
```

Please be aware that context injections with `@Context` will *not* work with `ResourceTestRule` by default because it's only using an simple in-memory container and not a full-fledged Servlet container.

You also seem to use a DI framework like Google Guice, Spring DI, or Jersey's HK2. These might also be the source of the NPE.

I'm closing this issue for now. Please feel free to add a comment if we should reopen this issue or if you can provide a complete reproducible test case.

**Closed by joschi** 2015-01-03 16:39 UTC

**Comment by yunspace** [comment] 2015-01-23 13:14
I'm currently in the process of testing out a dropwizard jersey2-guice (https://github.com/oillio/dropwizard-guice) enhancement and was able to reproduced this using the following test: https://github.com/yunspace/dropwizard-guice/blob/jersey2-guice/src/test/java/com/hubspot/dropwizard/guice/ServiceLocatorIntegrationTest.java

This is happening for both 0.8.0-rc3-SNAPSHOT and 0.8.0-rc2. Only the Resource Tests are effected. Integration Tests are work fine. Same line 634 in JerseyTest:

    try {
        setTestContainer(null).stop();
    } finally {
        closeIfNotNull(setClient(null));
    }

I tried to debug and track down why `setTestContainer` was returning NULL but haven't had much progress. Please assist. I will raise a issue with @oillio who write the jersey2-guice adaptation also.

**Comment by klette** [comment] 2015-01-26 09:33
@yunspace: I get that error if I have any Jersey 1.x jars in the classpath. So check if you got any 1.x libraries hanging around

**Comment by Larry0ua** [comment] 2015-01-31 10:15
Guys, as the topicstarter mentioned, the root cause of the problem is the 'Throw from Within Finally' antipattern used in ResourceTestRule.apply() - if an exception happens in the teardown it'll overwrite the original exception (which really should be debugged, not a teardown one). The cause of the problem of almost everyone is the mess in the classpath, but still we should see the problem, not a strange NPE from the junit/dropwizard implementation.

So my suggestion is to add a proper logging to the ResourceTestRule.apply (wrap finally block to one more try-catch, log the new exception but do not rethrow) and fix the problem in JerseyTest.tearDown() - handle the case when setTestContainer method returns null if there was no test container before (as setUp did not complete).

Once again - the real problem is that developers receive a strange NPE and not the exception they should fix, and this is the problem of the dropwizard code.

**Comment by yunspace** [comment] 2015-02-07 23:03
Thanks @klette, managed to resolve this by excluding Jersey dependencies in jersey2-guice:

    <dependency>
        <groupId>com.squarespace.jersey2-guice</groupId>
        <artifactId>jersey2-guice</artifactId>
        <version>0.5</version>
        <exclusions>
            <exclusion>
                 <groupId>org.glassfish.jersey.containers</groupId>
                 <artifactId>jersey-container-servlet-core</artifactId>
            </exclusion>
            <exclusion>
                <groupId>org.glassfish.jersey.containers</groupId>
                <artifactId>jersey-container-servlet</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

**Comment by drsnyder** [comment] 2015-03-25 00:29
> I tried to debug and track down why setTestContainer was returning NULL but haven't had much progress. Please assist. I will also raise a issue with @oillio who write the jersey2-guice adaptation.

In my case, in [this block in JerseyTest](https://github.com/jersey/jersey/blob/master/test-framework/core/src/main/java/org/glassfish/jersey/test/JerseyTest.java#L270-274), `old` is null so the call to `setTestContainer(null).stop();` ends up calling `stop()` on `null`.

Is this a dropwizard issue or a jersey one?

**Comment by drsnyder** [comment] 2015-03-25 05:51
@yunspace it looks like this issue is resolved in the latest version of jersey with this [code block that first checks to see if the old container is null](https://github.com/jersey/jersey/blob/master/test-framework/core/src/main/java/org/glassfish/jersey/test/JerseyTest.java#L634-637).

I tried to use a newer version of JerseyTest which seems to have resolved the issue.

```
    compile("io.dropwizard:dropwizard-testing:0.8.0") {
      exclude group: "org.glassfish.jersey.test-framework.providers"
    }
    compile "org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-inmemory:2.17"
```

**Comment by sudheshrajan** [comment] 2017-05-09 14:02
Surprisingly on changing my dropwizard-testing dependency 1.1.0, I receive the same error:

java.lang.NullPointerException
at io.dropwizard.testing.junit.ResourceTestRule$1.evaluate(ResourceTestRule.java:201)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

I have attached a cut down version of my code below: 

public class ProfileResourceTest extends BaseTest {

private static ProfileService profileService = mock(ProfileService.class);
private static AuthenticatedSession authenticatedSession = mockAuthenticatedSession();
private static UserProfile userProfileFixture = mockUserProfileFixture();

@Context
private ContainerRequest request;

@ClassRule
public static final ResourceTestRule resources = ResourceTestRule.builder()
        .setTestContainerFactory(new GrizzlyWebTestContainerFactory())
        .addResource(ProfileResource.class)
        .build();

    @Test
public void test_resource_getProfile_success() throws ProfileNotFoundException {
    // setup
    doReturn(userProfileFixture).when(profileService).getUserProfileByUserId(any());
    // execute
    UserProfile userProfile = resources.getJerseyTest().target("/v1/user-profile/")
            .request()
            .accept(MediaType.APPLICATION_JSON_TYPE)
            .get(UserProfile.class);

    // verify
    verify(profileService).getUserProfileByUserId(any());

    // assertNotNull(userProfile);
}
