### ISSUE TITLE
OptionalArgumentFactory and PostgreSQL

### ISSUE THREAD

**Issue by kilemensi** [dropwizard/dropwizard#894] opened 2015-02-23 15:20 UTC
When the `Optional` value is absent, PostgreSQL always fails with an exception: `org.postgresql.util.PSQLException: ERROR: could not determine data type of parameter $n`.

But changing `OptionalArgumentFactory` from

``` java
 statement.setNull(position, Types.OTHER);
```

to

``` java
statement.setNull(position, Types.VARCHAR);
```

seems to fix this problem. Anybody else has experienced this?

Postgresql JDBC: `9.4-1200-jdbc41` and `9.3-1102-jdbc41`
Dropwizard: All SNAPSHOTS and RC of `0.8.0`

**Comment by arteam** [comment] 2015-02-25 10:31
@kilemensi Thanks for the report. Which version of PostgreSQL and Java do you use?

Unfortunately, I can't reproduce your problem with the following test case:
````sql
create table departments(
  id bigint primary key,
  name varchar(32) not null
);

insert into departments(id, name) values (1, 'Sales'), (2,'Development'), 
(3, 'Accounting'), (4, 'IT');

create table employees(
  id bigint primary key,
  first_name varchar(32) not null,
  last_name varchar(32) not null,
  department_id bigint references departments(id)
);

insert into employees(id, first_name, last_name, department_id) values
(1, 'Jim', 'Fields', 2),
(2, 'Gregory', 'Dunn', 4),
(3, 'Lisa', 'Myers', 1),
(4, 'Colin', 'Wilson', 2),
(5, 'Jim', 'Button', 3),
(6, 'Den', 'Dunn', 3),
(7, 'Lisa', 'Hoffman', 3),
(8, 'Colin', 'Button', 1)
````

````sql
drop table employees;
drop table departments;
````

````java
public interface EmployeeDao {

    @SqlQuery("select id from employees " +
            "where first_name = :first_name " +
            "or    last_name = :last_name " +
            "or    department_id = :department_id")
    List<Long> find(@Bind("first_name") Optional<String> firstName,
                    @Bind("last_name") Optional<String> lastName,
                    @Bind("department_id") Optional<Long> departmentId);
}
````

````java
public class PostgresOptionalTest {

    Handle handle;
    EmployeeDao employeeDao;

    @Before
    public void setUp() throws Exception {
        DBI dbi = new DBI("jdbc:postgresql://127.0.0.1:5432/dw_optional", "dw", "pass");
        dbi.setSQLLog(new PrintStreamLog());
        dbi.registerArgumentFactory(new OptionalArgumentFactory(null));

        handle = dbi.open();
        handle.createScript("employees.sql").execute();
        employeeDao = handle.attach(EmployeeDao.class);
    }

    @After
    public void tearDown() throws Exception {
        handle.createScript("clear.sql").execute();
        handle.close();
    }

    @Test
    public void testFindByFirstName() {
        List<Long> result = employeeDao.find(Optional.of("Lisa"), Optional.absent(), Optional.absent());
        System.out.println(result);
        Assert.assertEquals(ImmutableList.of(3L, 7L), result);
    }

    @Test
    public void testFindByDepartment() {
        List<Long> result = employeeDao.find(Optional.absent(), Optional.absent(), Optional.of(2L));
        System.out.println(result);
        Assert.assertEquals(ImmutableList.of(1L, 4L), result);
    }
}
````

My configuration:
* dropwizard 0.8.0-rc3
* jdbi 2.59
* guava 18.0
* postgresql 9.4-1200-jdbc41
* PostgreSQL 9.3.5 on x86_64
* Java HotSpot(TM) Server VM (build 25.25-b02, mixed mode)

Can you, please, provide a test case where the error is reproduced?

**Comment by kilemensi** [comment] 2015-02-25 11:58
@arteam 

Sorry if I wasn't clear, the problem occurs when you're inserting a value into the database rather than when reading. If you use any complex statement, postgres looses type information on absent `Optional` value.

Using your example, lets make `last_name` null i.e.
```sql
create table employees(
  id bigint primary key,
  first_name varchar(32) not null,
  last_name varchar(32) null,
  department_id bigint references departments(id)
);
```

Lets then add the a complex insert into the `EmployeeDao` as shown below:
```java
    @SqlUpdate("WITH employee_info AS ("
            + "     SELECT :id AS id, :firstName AS first_name, "
            + "             :lastName AS last_name,"
            + "             :departmentId AS department_id"
            + " )"
            + " INSERT INTO employees (id, first_name, last_name,"
            + "          department_id)"
            + "     SELECT * FROM employee_info")
    int insert(@Bind("id") Long id,
            @Bind("firstName") String firstName,
            @Bind("lastName") Optional<String> lastName,
            @Bind("departmentId") Long departmentId);
```

Adding `testInsert` into `PostgresOptionalTest`
```java
    @Test
    public void testInsert() {
        final Long id = 10L;
        final String firstName = "Artem";
        final Long departmentId = 3L;

        final int insertCount = employeeDao.insert(id, firstName,
                Optional.<String>absent(), departmentId);
        Assert.assertEquals(1, insertCount);
    }
```
will thrown the exception in question.

**Comment by arteam** [comment] 2015-02-25 14:07
Aha, I now see your problem.
First, as a workaround you can specify a type excplicetely in the SQL query.
````java
@SqlUpdate("WITH employee_info AS ("
        + "     SELECT :id AS id, :firstName AS first_name, "
        + "             cast(:lastName AS VARCHAR) last_name,"
        + "             :departmentId AS department_id"
        + " )"
        + " INSERT INTO employees (id, first_name, last_name, department_id)"
        + " SELECT * FROM employee_info")
int insert(@Bind("id") Long id,
           @Bind("firstName") String firstName,
           @Bind("lastName") Optional<String> lastName,
           @Bind("departmentId") Long departmentId);
```` 

Speaking about a generic solution of this problem, it's not so easy. 
We have 2 major problems:
* Resolve a type binding of an `Optional` argument
* Figure out the correct SQL type for the corresponding Java type

The second problem can be solved by delegating it to JDBI's `BuiltInArgumentFactory`.
But the first is tough one. Information about a parametrized type can be get from the corresponding method through reflection. But  we don't have runtime information about a position of an 
argument, so it's impossible to say which parameter of the method is currently being handled.

I guess, to the best of my knowledge, we can't do anything about that now without 
assisting of JDBI.

**Comment by kilemensi** [comment] 2015-02-25 15:27
Yeah, I thought about adding explicit casts but I'm heavily using `Optional` in my code and hence would require a lot of casting.

I guess for now I'll stick to using my custom `OptionalArgumentFactory`.

**Comment by nickbabcock** [comment] 2016-10-22 14:37
I'm not sure what has changed, but I'm using Drowpizard 1.0.2, Postgres, and JDBI for a project and the following binds work fine without needing to cast:

```java
@Bind("a") OptionalLong a,
@Bind("b") Optional<LocalDateTime> b,
@Bind("c") String c,
@Bind("d") Optional<byte[]> d
```

I'll close this issue in a few weeks time if no new info is presented.

**Comment by kilemensi** [comment] 2016-10-23 14:30
Hi @nickbabcock 

The issue was when Optional is **empty**, dropwizard/jdbi could not figure out what type (it worked fine otherwise) of null it was. To quote @arteam:

> Information about a parametrized type can be derived from the corresponding method through reflection. But we don't have runtime information about a position of an argument, so it's impossible to say which parameter of the method is currently being handled

I still think this is the case but since I'm in the home streatch of another project, I can't really test to see if the situation has really been fixed or not in the project I was working on when I reported this issue.

**Comment by nickbabcock** [comment] 2016-10-23 16:27
I'm optimistic that this may be fixed, as I can confirm that optionals that are empty are being persisted as `null`

**Comment by nickbabcock** [comment] 2017-02-08 01:35
I'm closing this because I have several apps in production using Dropwizard 1.0 + jdbi + postgres (9.5.5 server with 9.4-1212 driver) + empty java.util optionals, and I see empty optionals persisted as null.

If the erroneous behavior still persists for the latest versions, please post a repo for me to cross examine.

**Closed by nickbabcock** 2017-02-08 01:35 UTC
