### ISSUE TITLE
Critical bug in Jackson for null values in Dropwizard 0.8.4

### ISSUE THREAD

**Issue by carminexx** [dropwizard/dropwizard#1294] opened 2015-10-22 14:49 UTC
I just noticed a critical bug that makes Jackson deserialization impossible in Dropwizard 0.8.4 (0.8.3 and lower seems not to be affected by this bug).
When I try to deserialize (eg: pass a JSON to a resource) an JSON that contains at least one field with value "null", the whole stack fails and Jersey sends a 500 error.

Here's the stacktrace:
```
WARN  [2015-10-22 14:00:31,419] org.eclipse.jetty.servlet.ServletHandler: 
! java.lang.NoSuchFieldError: _nullProvider
! at com.fasterxml.jackson.module.afterburner.deser.OptimizedSettableBeanProperty._deserializeString(OptimizedSettableBeanProperty.java:161) ~[jackson-module-afterburner-2.5.1.jar:2.5.1]
! at com.fasterxml.jackson.module.afterburner.deser.SettableStringMethodProperty.deserializeAndSet(SettableStringMethodProperty.java:54) ~[jackson-module-afterburner-2.5.1.jar:2.5.1]
! at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserializeFromObject(SuperSonicBeanDeserializer.java:240) ~[jackson-module-afterburner-2.5.1.jar:2.5.1]
! at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:122) ~[jackson-module-afterburner-2.5.1.jar:2.5.1]
! at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1470) ~[jackson-databind-2.6.0.jar:2.6.0]
! at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:912) ~[jackson-databind-2.6.0.jar:2.6.0]
! at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:808) ~[jackson-jaxrs-base-2.5.1.jar:2.5.1]
! at io.dropwizard.jersey.jackson.JacksonMessageBodyProvider.readFrom(JacksonMessageBodyProvider.java:60) ~[dropwizard-jersey-0.8.4.jar:0.8.4]
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:74) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:852) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:270) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.internal.inject.EntityParamValueFactoryProvider$EntityValueFactory.provide(EntityParamValueFactoryProvider.java:96) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.provide(ParamValueFactoryWithSource.java:71) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:93) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:127) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:309) ~[jersey-server-2.21.jar:na]
! ... 46 common frames omitted
! Causing: org.glassfish.jersey.server.ContainerException: java.lang.NoSuchFieldError: _nullProvider
! at org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:256) ~[jersey-container-servlet-core-2.21.jar:na]
! at org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:238) ~[jersey-container-servlet-core-2.21.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:486) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:317) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:292) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1139) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:460) ~[jersey-container-servlet-core-2.21.jar:na]
! ... 37 common frames omitted
! Causing: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoSuchFieldError: _nullProvider
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:485) ~[jersey-container-servlet-core-2.21.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) ~[jersey-container-servlet-core-2.21.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334) ~[jersey-container-servlet-core-2.21.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221) ~[jersey-container-servlet-core-2.21.jar:na]
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) ~[dropwizard-jetty-0.8.4.jar:0.8.4]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) ~[jetty-servlets-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300) ~[jetty-servlets-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:134) ~[dropwizard-jetty-0.8.4.jar:0.8.4]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) ~[dropwizard-servlets-0.8.4.jar:0.8.4]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:44) ~[dropwizard-jersey-0.8.4.jar:0.8.4]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39) ~[dropwizard-jersey-0.8.4.jar:0.8.4]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:259) ~[jetty-servlets-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:222) ~[jetty-servlets-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [metrics-jetty9-3.1.1.jar:3.1.1]
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [dropwizard-jetty-0.8.4.jar:0.8.4]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.Server.handle(Server.java:497) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
WARN  [2015-10-22 14:00:31,422] org.eclipse.jetty.server.HttpChannel: /my/resource
! java.lang.NoSuchFieldError: _nullProvider
! at com.fasterxml.jackson.module.afterburner.deser.OptimizedSettableBeanProperty._deserializeString(OptimizedSettableBeanProperty.java:161) ~[jackson-module-afterburner-2.5.1.jar:2.5.1]
! at com.fasterxml.jackson.module.afterburner.deser.SettableStringMethodProperty.deserializeAndSet(SettableStringMethodProperty.java:54) ~[jackson-module-afterburner-2.5.1.jar:2.5.1]
! at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserializeFromObject(SuperSonicBeanDeserializer.java:240) ~[jackson-module-afterburner-2.5.1.jar:2.5.1]
! at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:122) ~[jackson-module-afterburner-2.5.1.jar:2.5.1]
! at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1470) ~[jackson-databind-2.6.0.jar:2.6.0]
! at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:912) ~[jackson-databind-2.6.0.jar:2.6.0]
! at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:808) ~[jackson-jaxrs-base-2.5.1.jar:2.5.1]
! at io.dropwizard.jersey.jackson.JacksonMessageBodyProvider.readFrom(JacksonMessageBodyProvider.java:60) ~[dropwizard-jersey-0.8.4.jar:0.8.4]
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:74) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:852) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:270) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.internal.inject.EntityParamValueFactoryProvider$EntityValueFactory.provide(EntityParamValueFactoryProvider.java:96) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.provide(ParamValueFactoryWithSource.java:71) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:93) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:127) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:309) ~[jersey-server-2.21.jar:na]
! ... 46 common frames omitted
! Causing: org.glassfish.jersey.server.ContainerException: java.lang.NoSuchFieldError: _nullProvider
! at org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:256) ~[jersey-container-servlet-core-2.21.jar:na]
! at org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:238) ~[jersey-container-servlet-core-2.21.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:486) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:317) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) ~[jersey-common-2.21.jar:na]
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:292) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1139) ~[jersey-server-2.21.jar:na]
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:460) ~[jersey-container-servlet-core-2.21.jar:na]
! ... 37 common frames omitted
! Causing: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoSuchFieldError: _nullProvider
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:485) ~[jersey-container-servlet-core-2.21.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) ~[jersey-container-servlet-core-2.21.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334) ~[jersey-container-servlet-core-2.21.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221) ~[jersey-container-servlet-core-2.21.jar:na]
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) ~[dropwizard-jetty-0.8.4.jar:0.8.4]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) ~[jetty-servlets-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300) ~[jetty-servlets-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:134) ~[dropwizard-jetty-0.8.4.jar:0.8.4]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) ~[dropwizard-servlets-0.8.4.jar:0.8.4]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:44) ~[dropwizard-jersey-0.8.4.jar:0.8.4]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39) ~[dropwizard-jersey-0.8.4.jar:0.8.4]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:259) ~[jetty-servlets-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:222) ~[jetty-servlets-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) ~[metrics-jetty9-3.1.1.jar:3.1.1]
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) ~[dropwizard-jetty-0.8.4.jar:0.8.4]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.Server.handle(Server.java:497) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) ~[jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
```

**Comment by joschi** [comment] 2015-10-22 15:15
@carminexx Please provide a minimal example project to reproduce this bug.

**Comment by carminexx** [comment] 2015-10-22 15:19
Any resource that consumes a java POJO as request body:

    @POST
    public Response myResource(MyPOJO myPojo)

And, assuming your POJO is like:

```class MyPOJO {
      private String one;
      private String two;
}```

Pass it JSON-serialized to the resource, with at least one field with null value:

```{
     "one" :  "something",
     "two" : null,
}```

**Comment by CrossfireCurt** [comment] 2015-10-22 18:47
I am experiencing this issue on 0.8.3.

**Comment by CrossfireCurt** [comment] 2015-10-22 19:43
Looks like I was using a jackson package that was too new:
```
com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.6.3
```

Changed it to
```
com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.5.
```

now it works!

**Comment by joschi** [comment] 2015-10-23 07:50
@CrossfireCurt Thanks for the hint!
@carminexx Is it possible that a similar problem (i. e. dependency divergence) is responsible for your problem?

**Comment by joschi** [comment] 2015-10-25 18:21
Closing issue as I couldn't reproduce the problem and the original author didn't respond.

**Closed by joschi** 2015-10-25 18:21 UTC
Labels: bug

**Comment by carminexx** [comment] 2015-10-26 10:16
Sorry for late reply.
As @CrossfireCurt noted, the problem was due to another Jackson dependency, that was the 2.6 version instead of the 2.5 required by drop wizard. Oddly, in 0.8.3 and lower everything worked even if Jackson version was 2.6

**Comment by joschi** [comment] 2015-10-26 10:45
@carminexx Thanks for the update!

**Comment by pramit11** [comment] 2015-12-30 17:13
I also faced the same issue. Found the exact reason for error. Here, jackson afterburner module version is jackson-module-afterburner-2.5.1, while jackson databind version is jackson-databind-2.6.0. Jackson afterburner directly depends on databind, hence they should be compatible version, so same version should resolve the issue, either both 2.5 or both 2.6 or later.
In this particular case, there is an attribute called _nullProvider, which afterburner is using from databind, and it was removed in 2.6.

**Comment by MalsR** [comment] 2016-01-28 09:39
Hi All,
We also experienced the same problem with jackson 2.6.2 and older version of dropwizard 0.7.1 to be precise. We had the same stacktrace as @carminexx did. We reproduced this issue by having a json payload with a null value. e.g. "exampleAttribute": null

Upgrading the jackson version to 2.6.5 has fixed the issue for us. I had a look at the Jackson issues list to see if there was a particular bug raised for the fix but could not find any. Does anyone else know? 

Thanks
Mals

**Comment by nikhil578** [comment] 2016-01-29 07:10
Upgrading to jackson version to 2.6.5 doesn't fix this problem with dropwizard 0.8.3.

**Comment by joschi** [comment] 2016-01-29 09:32
@nikhil578 Upgrading arbitrary dependencies won't help in this case, as the problem was caused by incompatible Jackson dependencies.

Check your dependency tree with `mvn dependency:tree` and make sure that all Jackson dependencies are pulled in with their correct versions.

**Comment by devindi** [comment] 2016-07-27 16:24
Fixed this issue by updating jackson-module-afterburner like this

```
compile ('io.dropwizard:dropwizard-core:0.8.1')
                {exclude group: 'com.fasterxml.jackson.module', module: 'jackson-module-afterburner'}
compile 'com.fasterxml.jackson.module:jackson-module-afterburner:2.6.7'
```
