### ISSUE TITLE
0.9.0 Metrics configuration issue

### ISSUE THREAD

**Issue by sheldon-sminq** [dropwizard/dropwizard#1317] opened 2015-10-30 06:35 UTC
I just upgraded to 0.9.0 and get the following error while lunching application

Exception in thread "main" javax.validation.UnexpectedTypeException: HV000186: The constraint of type 'javax.validation.constraints.NotNull' defined on 'metrics.reporters[0].frequency' has multiple matching constraint validators which is due to an additional value handler of type 'io.dropwizard.validation.valuehandling.OptionalValidatedValueUnwrapper'. It is unclear which value needs validating. Clarify configuration via @UnwrapValidatedValue.

My metrics configuration in yml

metrics:
  reporters:
    - type: console
      timeZone: Asia/Kolkata
      output: stdout
      durationUnit: milliseconds
      rateUnit: seconds
       frequency: 1 minute

**Comment by joschi** [comment] 2015-10-30 09:02
Duplicate of #1308.

**Closed by joschi** 2015-10-30 09:02 UTC
