### ISSUE TITLE
No request logs in dropwizard 1.0.1

### ISSUE THREAD

**Issue by m-at-nu** [dropwizard/dropwizard#1737] opened 2016-09-23 12:10 UTC
Hello,
since I've updated dropwizard to version 1.0.1 I have no request logs anymore, using dropwizard version 1.0.0 everything works. Is this a known bug or was anything changed regarding the configuration? According to the [release logs](https://github.com/dropwizard/dropwizard/blob/master/docs/source/about/release-notes.rst#v101-sep-21-2016), issue #1678 may be related to this? Even so, having only the requestLog's appenders without logging appenders doesn't work either with version 1.0.1.

I've attached my server configuration _server.yml_ file below:
```
server:
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8080
  requestLog:
    appenders:
      - type: console
logging:
  appenders:
    - type: console
````
I've also attached a small minimal working example. Please change the dropwizard version to 1.0.0 and 1.0.1 respectively to test the issue.

Thanks in advance!
[test.zip](https://github.com/dropwizard/dropwizard/files/489626/test.zip)

**Comment by nickbabcock** [comment] 2016-09-23 13:20
I can confirm that this is a bug affecting v1.0.1

@m-at-nu correctly identified where the bug was introduced.

I can also confirm that checking out the 1.0.x branch, the following command fixed the issue

```
git revert -m 1 e7c16c97
```

**Comment by arteam** [comment] 2016-09-23 13:26
Yes, I can also confirm this regression. Which is strange, because it's exactly the problem which had to fixed by #1678. I would like to get some feedback from @evnm and @tjcutajar before reverting the commit.

**Comment by arteam** [comment] 2016-09-23 13:38
Oh, now I see @tjcutajar pointed out to this problem in #1672, we ignored his comment. How inconsiderate of us.

**Comment by arteam** [comment] 2016-09-23 14:25
Digging into internals I see that logback doesn't log messages because of a `NullPointerException` in `org.eclipse.jetty.server.Request#extractQueryParameters` method because the `metadata` object is null.

**Comment by arteam** [comment] 2016-09-23 14:30
It looks like there is a race between calling the `org.eclipse.jetty.server.Request#recycle` method by Jetty and extracting information from the request by Logback.

**Comment by evnm** [comment] 2016-09-23 14:45
Those are the same Logback codepaths that I've been spelunking in while debugging #1699. There seems to be a growing number of fingers pointing to Dropwizard's Logback-enabled request logging.

**Comment by tjcutajar** [comment] 2016-09-23 15:14
This is a duplicate of #1686 

Apologies that perhaps the title and description of it is not clear. Considering the state of request logging is actually worse than it was before it makes sense for #1678 to be reverted.

**Comment by arteam** [comment] 2016-09-23 18:26
I've pushed to the Maven Central Repository Dropwizard 1.0.2 which reverts #1678. Should be available in a couple of hours.

**Comment by arteam** [comment] 2016-09-26 17:19
Dropwizard 1.0.2 has been [published|http://mvnrepository.com/artifact/io.dropwizard/dropwizard-core/1.0.2] to the Maven Central repository.

**Comment by m-at-nu** [comment] 2016-09-27 07:00
Thanks a lot! In version 1.0.2 both loggers are working again :-).

**Comment by joschi** [comment] 2016-09-27 07:34
@m-at-nu Thanks for your feedback!

**Closed by joschi** 2016-09-27 07:34 UTC
Labels: bug
