### ISSUE TITLE
Add a factory for reporting with PickledGraphite

### ISSUE THREAD

**Issue by mwhipple** [dropwizard/dropwizard#1642] opened 2016-07-24 22:29 UTC
Support for sending pickled graphite metrics was added to https://github.com/dropwizard/metrics/blob/3.2-development/metrics-graphite/src/main/java/com/codahale/metrics/graphite/PickledGraphite.java but a complementary factory implementation has not been added to Dropwizard.

(This is a reminder to myself to do this and submit a PR unless its done in the interim)

**Comment by nickbabcock** [comment] 2016-07-25 00:15
Closing as a duplicate of #1442

**Closed by nickbabcock** 2016-07-25 00:15 UTC
