### ISSUE TITLE
Dependency on glassfish hk2 version 2.4.0-b31 missing Java 8 profile fix in version 2.4.0

### ISSUE THREAD

**Issue by PeterGroesbeck** [dropwizard/dropwizard#1426] opened 2016-01-20 19:15 UTC
The fix for the profile javadoc-jdk8+ in glassfish hk2's parent pom detailed in this ticket does not appear to have made it into Dropwizard's version of that dependency: https://java.net/jira/browse/HK2-277

The result is that I am unable to pull in Dropwizard as a dependency on a project using a version of Maven later than 3.0.3.

**Comment by nickbabcock** [comment] 2016-01-20 20:29
Closing as a dupe of #1335 and #1325, if not a dupe, let us know what's different.

**Closed by nickbabcock** 2016-01-20 20:29 UTC
