### ISSUE TITLE
Using PatternLayout in File Appender logging DW 1.1.0

### ISSUE THREAD

**Issue by kedarjavalkar** [dropwizard/dropwizard#2141] opened 2017-09-01 08:56 UTC
I want to log api requests into file logger. I have explored [Request Log](http://www.dropwizard.io/1.1.0/docs/manual/configuration.html#request-log) and it lead to [Access Pattern Layout](https://logback.qos.ch/manual/layouts.html#AccessPatternLayout). But im unsure of how to configure the logger which can log
`INFO   [2017-09-01 07:05:14,602] u.p.a.u.AuditMessage - something i'm logging`
and 
`0:0:0:0:0:0:0:1 - - [01/Sep/2017:07:05:14 +0000] "POST /api/mobile/user/login HTTP/1.1" 200 1737 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" 102`
into same file. As i want the log file to be archived and rotated

**Comment by nickbabcock** [comment] 2017-09-01 14:29
Is this a dupe of https://github.com/dropwizard/dropwizard/issues/1731?

**Comment by kedarjavalkar** [comment] 2017-09-01 14:50
Guess so. If im able to log into two different files and it is also archived then it will solve my requirement

**Comment by nickbabcock** [comment] 2017-09-01 15:00
Yup that's what I do. A file for the request log and a file for application log. Both are archived and rotated.

**Comment by nickbabcock** [comment] 2018-06-22 12:13
Closing this as the issue appears to be a dupe or solved, respond back if not

**Closed by nickbabcock** 2018-06-22 12:13 UTC
