### ISSUE TITLE
Hibernate insert/update exceptions not being returned to the client

### ISSUE THREAD

**Issue by apgeorge** [dropwizard/dropwizard#1604] opened 2016-06-22 11:06 UTC
**Version: 1.0.0RC3**

The fix to allow lazy loading of POJOs during serialization has introduced a key issue. We are no longer seeing SQLExceptions during an insert/update//delete being reported back to the client.

In 1.0.0RC3, the session will be closed and the transaction committed only after the serialization has happened. If there are any database exceptions during the transaction commit (column val exceed/constraints etc..), they now happen only after the serialized response has been sent back. So the client assumes things are fine, but actually the server logs show the exception.

I guess we will still need to end the transaction or commit it in the RESP_FILTERS_START event. And session can be closed in FINISHED event. 

Here's the pull that introduced this issue, https://github.com/dropwizard/dropwizard/pull/1466

**Comment by arteam** [comment] 2016-06-23 07:56
Thanks for bringing this issue to our attention. Could you provide a test case/sample project for reproducing it? We currently have a test case for handling SQL exceptions with Hibernate DAOs, but I guess your use case is a little bit different. Do you use manual Hibernate session management?

/cc @ant3

**Comment by ant3** [comment] 2016-06-23 13:23
I agree that there is a potential issue here.  Sorry - my fault.  The suggested solution should work as far as I can see.

When I wrote the code at issue I assumed that user code would manage transactions, but it is perfectly reasonable to leave this to the framework, so it is indeed an issue.

I will have a look at creating a fix, but I'm a bit busy for the next few days so it won't be immediate I'm afraid.

**Comment by arteam** [comment] 2016-06-30 08:36
I think this issue is the only blocker to release 1.0.0.

We need a test case to reproduce it, though. Otherwise I don't see how we can fix it. We can't rollback to committing a transaction on the `RESP_FILTERS_FINISHED` event, because it breaks tests for lazy loading,

**Comment by ant3** [comment] 2016-07-01 12:00
Sorry for the delay.  This came at an awkward time for me.  I will try to create a fix today or tomorrow.

**Comment by ant3** [comment] 2016-07-02 23:24
I have had chance to look more at this, and I am having problems reproducing the issue.
I created a test that causes a constraint violation when the transaction commits, but as far as I can see, the exception thrown in the FINISHED event is still before the response has been sent - and the ON_EXCEPTION event still triggers.  So I still get a sensible error response.

I can put this test in a pull request if that is useful, but I can't make it fail (in a meaningful way) so I'm not sure it has much value.

@apgeorge, can you tell me in detail what your code does to generate this error, or even better submit a test case.

**Comment by ant3** [comment] 2016-07-02 23:28
I have committed the test to my fork but won't create a PR.

**Comment by apgeorge** [comment] 2016-07-03 19:26
Sure, will take a shot at the test case tomorrow. Thanks.

**Comment by apgeorge** [comment] 2016-07-05 18:17
@ant3 I gave this a shot today and here are my findings.

1. We couldn't replicate the issue in the test that you commited.
The only key difference between what your test does and what we are doing is that we return the created domain object back from the resource method. Tried modifying your test to do the same but that still didn't replicate the issue.

2. We tried to replicate this issue in our own integration tests but we still couldn't replicate it. So, the integration test fails as expected, but the behaviour on the app is different. We get 500 return in test but 200 in the app.

3. When we downgrade to RC2, we no longer face this issue.

4. Setting the lazy flag to false in the hibernate bundle doesn't resolve the issue.

I wonder if this is because during the tests the event handling happens to run synchronous, but whereas in the app it's asynchronous? I haven't had a chance to look at the dropwizard code yet, but this is my hunch as of now.

**Comment by pkwarren** [comment] 2016-07-06 01:40
I'm not very familiar with Hibernate, but after changing the test to run as a full integration test, I was able to fail the test in @ant3's repository (it appears that the JSON response is serialized however a content-type header isn't sent in the response). I don't know if this is the underlying issue seen by the reporter.

Here's what I put together (including the proposed fix mentioned above which moves the closing of the session to occur in the `FINISHED` event and the transaction to be committed in the `RESP_FILTERS_START` event: https://github.com/dropwizard/dropwizard/compare/master...pkwarren:lazyload

**Comment by ant3** [comment] 2016-07-06 22:10
@pkwarren: Thanks for this.  My knowledge of the dropwizard test infrastructure is obviously less that yours :-).  What you have done is broadly what I think needs to be done.

@apgeorge: Does the fix from @pkwarren fix your issue?  I think it should.

@arteam: The fix involves changes to the Aspect code, which I think you originally wrote.  What are your thoughts?

**Comment by arteam** [comment] 2016-07-07 08:16
I had a looks and the patch seems to be fix the issue. I picked up @pkwarren's changes as a baseline, made some improvements and submitted a pull request #1620.
 
@ant3, @pkwarren, @apgeorge  please review.

**Comment by ant3** [comment] 2016-07-07 14:37
These changes look sensible to me.  One minor comment:
In LazyLoadingTest the estApplication (line 51) uses lazy loading, but the LazyTestApplication (line 94) doesn't use it.  This seems a bit confusing.

**Comment by arteam** [comment] 2016-07-07 14:47
You are right, will fix the class name.

**Closed** 2016-07-08 07:26 UTC
Labels: bug
