### ISSUE TITLE
Testing Resources with @Context HttpServletResponse parameters

### ISSUE THREAD

**Issue by digital-abyss** [dropwizard/dropwizard#2027] opened 2017-04-25 22:05 UTC
I suspect this is an identical issue to https://github.com/dropwizard/dropwizard/issues/651 but haven't been able to come up with a working answer -- I'm using dropwizard version 0.6.2 (It isn't possible at this time to upgrade).

I have resources where we use `@Context` e.g.:
```
@GET
@Path("/{fileId}/data")
@Produces("application/octet-stream")
public Response getData(
			@Context HttpServletResponse response,
			@ApiParam(value = "ID of the target file", required = true) @PathParam("fileId") Id fileId ) {
//....
response.setHeader(/*...*/);
//... stream is some StreamingOutput
return Response.ok(stream).build();
  }
```

I would like to be able to test these endpoints using dropwizard-testing, but hit the same error as the other issue:

```
SEVERE: Missing dependency for method public javax.ws.rs.core.Response MyResource.getData(javax.servlet.http.HttpServletResponse,org.vena.id.Id,) throws java.lang.Exception at parameter at index 0
```

`ResourceTestRule` doesn't seem to exist in dropwizard 0.6.2 --- are there any alternatives ?

**Comment by nickbabcock** [comment] 2017-04-26 14:08
0.6.2 contains `ResourceTest` which you may be able to configure the jersey test to use an actual servlet container.

Since 0.6.2 isn't supported anymore I'm going to close this issue, as if it is not possible in 0.6.2 the feature won't be backported, but feel free to respond with the answer once you've confirmed it so that others in the same situation as you will benefit.

**Closed by nickbabcock** 2017-04-26 14:08 UTC
