### ISSUE TITLE
[dropwizard-swagger] TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by greg771377** [dropwizard/dropwizard#5406] opened 2022-06-15 18:20 UTC
Hello,

I am using "smoketurner/dropwizard-swagger v2.0.12-1" with "dropwizard-core v2.1.0".
I don't understand why swagger cannot execute the API. I get "TypeError: Cannot read properties of null" in the browser console.
Please find below my screenshots.

Here my swagger.json file. Note: the swagger.json is valid, I checked it in Swagger Editor.
![image](https://user-images.githubusercontent.com/28727396/173849690-54683c75-1a12-424a-a144-9f14c3613b7b.png)

When I click on Execute Button I get the swagger error:
![image](https://user-images.githubusercontent.com/28727396/173849805-0c0a75c4-f4a1-422f-8fd4-34b57ed77be4.png)

And here the browser console error:
![image](https://user-images.githubusercontent.com/28727396/173849609-a964a3b2-86c8-4712-acc3-508afacf33e4.png)

And here the Java code that exposers the Test method:
![image](https://user-images.githubusercontent.com/28727396/173850337-d18e4827-c6c7-43c2-9645-2f081bed6e83.png)

![image](https://user-images.githubusercontent.com/28727396/173850139-b0cc2d07-4b8d-4a0d-aac7-b3d6d96bd20f.png)

Thanks in advance 4 your help.
Greg

**Comment by joschi** [comment] 2022-06-18 12:49
Duplicate of https://github.com/smoketurner/dropwizard-swagger/issues/273.

**Closed as completed by joschi** 2022-06-18 12:49 UTC

**Comment by sasirekhamsvl** [comment] 2023-11-07 07:34
is solution found for this?
