### ISSUE TITLE
Size based rollover logging still broken in 1.0.2

### ISSUE THREAD

**Issue by looppair** [dropwizard/dropwizard#1789] opened 2016-10-28 14:22 UTC
It looks `maxFileSize` handling was not fixed in #1691. Since upgrading past 0.9.3 the following configuration results in no request log at all:

```
server:
  type: default
  applicationConnectors:
    - type: http
      port: 80
  adminConnectors:
    - type: http
      port: 8081
  registerDefaultExceptionMappers: false
  requestLog:
    appenders:
      - type: console
      - type: file
        currentLogFilename: /var/log/service_name/request.log
        archivedLogFilenamePattern: /var/log/service_name/request.log.%i
        maxFileSize: 50MB
```

The following configuration results in a working request log at `/var/log/service_name/request.log`:

```
server:
  type: default
  applicationConnectors:
    - type: http
      port: 80
  adminConnectors:
    - type: http
      port: 8081
  registerDefaultExceptionMappers: false
  requestLog:
    appenders:
      - type: console
      - type: file
        currentLogFilename: /var/log/service_name/request.log
        archivedLogFilenamePattern: /var/log/service_name/request.log.%d
```

I tested these using 1.0.2, and can confirm that the full configuration (only slightly more complex) works in 0.9.2 and 0.9.3, and fails in 1.0.0, 1.0.1 and 1.0.2.

Size based log rotation is important for my project because we're working with limited disk space.

**Comment by arteam** [comment] 2016-10-28 17:46
Hello, @looppair. 

Thanks for pointing this out! I've backported ab65a32 (the commit which fixes the size based rollover) to the 1.0.x branch and released Dropwizard 1.0.3. It should be available in the Maven Central repository in a couple of hours. Let me know, if the issue is fixed in this version.

**Comment by arteam** [comment] 2016-11-08 08:10
Hello, @looppair!

Could you please verify whether Dropwizard 1.0.3 solves your issue or not. Thanks.

**Comment by Wstunes** [comment] 2016-11-16 14:09
hello @arteam 
It seems that you are familiar with the logging part. Could you please help me in https://github.com/dropwizard/dropwizard/issues/1827 ?

**Comment by nickbabcock** [comment] 2016-11-26 22:12
Closing as this is fixed.

**Closed by nickbabcock** 2016-11-26 22:12 UTC
Labels: bug
