### ISSUE TITLE
Which third-party module has Google Guice working with 1.0.0-rc2 ?

### ISSUE THREAD

**Issue by who** [dropwizard/dropwizard#1522] opened 2016-04-18 20:53 UTC
The current module that we use for Guice integration, `com.hubspot.dropwizard:dropwizard-guice` is no longer updated and is falling far behind the current version of Dropwizard. (See https://github.com/HubSpot/dropwizard-guice/issues/79 )

Do any third-party modules enable Google Guice usage on Dropwizard 1.0.0-rc2, or is there another recommended way to perform dependency injection in 1.0.0-rc2 ?

**Comment by trasa** [comment] 2016-04-18 21:50
something like https://github.com/xvik/dropwizard-guicey ?

**Comment by Randgalt** [comment] 2016-04-19 03:36
http://soabase.io/guice.html

I wrote this which is compatible with the old Jersey-Guice but works with Jersey 2.0

-Jordan

**Comment by bladecatcher** [comment] 2016-04-19 03:43
I have migrated from HubSpot's dropwizard-guice to soabase and it's worked
great for me so far with Dropwizard 1.0.0 . soabase solves the big problem
of Guice injection into Jersey 2 resources

**Comment by joschi** [comment] 2016-04-19 08:10
There's been a related topic on the dropwizard-dev mailing list recently: https://groups.google.com/forum/#!searchin/dropwizard-dev/guice/dropwizard-dev/EVem62Gc_SY/LKypTx2KBAAJ

I'm closing this issue because it's not a bug report or feature request for Dropwizard.

**Closed by joschi** 2016-04-19 08:10 UTC

**Comment by vvondra** [comment] 2016-05-24 06:37
@joschi It could be a nice addition to the documentation, since people will be often looking for this.
