### ISSUE TITLE
Local build fails on mac

### ISSUE THREAD

**Issue by head-thrash** [dropwizard/dropwizard#1714] opened 2016-08-30 14:50 UTC
A day is spent trying to understand WTF.

dw-core module build fails with test failure.

`DefaultServerFactoryTest.testGracefulShutdown()` somehow affects `SimpleServerFactoryTest.testBuild()`.

Both maven and idea cases produce the same.

If I switch order of those tests, they are green.

`testBuild` fails trying to execute the task, essentially, because of query parameters collection of the request is not parsed (for the unknown reason):

```
assertThat(httpRequest("POST", "http://localhost:" + port + "/secret/tasks/hello?name=test_user"))
     .isEqualTo("Hello, test_user!");
```

Debugging of that reveals... strange stuff (see attached image):

<img width="723" alt="screen shot 2016-08-30 at 16 53 52" src="https://cloud.githubusercontent.com/assets/892781/18093707/d9813564-6ee1-11e6-8502-9b266b782550.png">

(Here, `_metaData` field of `org.eclipse.jetty.server.Request` is not null, however, the local variable assigned is `null`, and the parsing of the task request is failed)

This occurs _almost_ in any case, so the issue is... well, floating.

Anybody, any ideas how to fix or resolve that?:)
Java version is: 1.8.0_92-b14

**Comment by nickbabcock** [comment] 2016-08-30 15:00
Thanks for the additional info, this is currently a known issue. Closing as a dupe of #1699

**Closed by nickbabcock** 2016-08-30 15:00 UTC
